// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package store

import (
	"context"
)

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE "Notification" SET "read" = true WHERE "userId" = $1
`

func (q *Queries) MarkNotificationsRead(ctx context.Context, userid string) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, userid)
	return err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE "User" SET
    "name" = COALESCE($1::text, "name"),
    "nickname" = COALESCE($2::text, "nickname"),
    "school" = COALESCE($3::text, "school"),
    "grade" = COALESCE($4::text, "grade"),
    "privacy" = COALESCE($5::jsonb, "privacy"),
    "completedSubjects" = COALESCE($6::text[], "completedSubjects"),
    "srsMode" = COALESCE($7::text, "srsMode"),
    "desiredRetention" = COALESCE($8::double precision, "desiredRetention")
WHERE "id" = $9
RETURNING id, name, nickname, role, school, grade, streak, points, suspended, "selectedChildId", "srsMode", "desiredRetention", privacy, "completedSubjects", "linkFailures", "linkLockedUntil", "createdAt"
`

type UpdateProfileParams struct {
	Name              *string
	Nickname          *string
	School            *string
	Grade             *string
	Privacy           []byte
	CompletedSubjects []string
	SrsMode           *string
	DesiredRetention  *float64
	ID                string
}

// A NULL argument keeps the column, so the handler sends only the fields the client provided,
// exactly like the previous server's partial update.
func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.Name,
		arg.Nickname,
		arg.School,
		arg.Grade,
		arg.Privacy,
		arg.CompletedSubjects,
		arg.SrsMode,
		arg.DesiredRetention,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Role,
		&i.School,
		&i.Grade,
		&i.Streak,
		&i.Points,
		&i.Suspended,
		&i.SelectedChildID,
		&i.SrsMode,
		&i.DesiredRetention,
		&i.Privacy,
		&i.CompletedSubjects,
		&i.LinkFailures,
		&i.LinkLockedUntil,
		&i.CreatedAt,
	)
	return i, err
}
