// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"
)

const createSchool = `-- name: CreateSchool :one
INSERT INTO "School" ("id", "name") VALUES ($1, $2) RETURNING id, name
`

type CreateSchoolParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateSchool(ctx context.Context, arg CreateSchoolParams) (School, error) {
	row := q.db.QueryRow(ctx, createSchool, arg.ID, arg.Name)
	var i School
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listAdminReports = `-- name: ListAdminReports :many
SELECT r.id, r."userId", r."postId", r.reason, r.status, r."createdAt", p."title" AS post_title
FROM "Report" AS r JOIN "Post" AS p ON p."id" = r."postId"
ORDER BY r."createdAt" DESC
LIMIT 500
`

type ListAdminReportsRow struct {
	Report    Report
	PostTitle string
}

func (q *Queries) ListAdminReports(ctx context.Context) ([]ListAdminReportsRow, error) {
	rows, err := q.db.Query(ctx, listAdminReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminReportsRow{}
	for rows.Next() {
		var i ListAdminReportsRow
		if err := rows.Scan(
			&i.Report.ID,
			&i.Report.UserID,
			&i.Report.PostID,
			&i.Report.Reason,
			&i.Report.Status,
			&i.Report.CreatedAt,
			&i.PostTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminSchools = `-- name: ListAdminSchools :many
SELECT id, name FROM "School"
ORDER BY "name" ASC
LIMIT 1000
`

func (q *Queries) ListAdminSchools(ctx context.Context) ([]School, error) {
	rows, err := q.db.Query(ctx, listAdminSchools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminUsers = `-- name: ListAdminUsers :many

SELECT "id", "name", "nickname", "role", "suspended"
FROM "User"
ORDER BY "createdAt" DESC
LIMIT 500
`

type ListAdminUsersRow struct {
	ID        string
	Name      string
	Nickname  string
	Role      Role
	Suspended bool
}

// Admin: the moderation overview, report triage and the school directory (api.ts admin).
// Suspending an account uses UpdateUserSuspended from users.sql.
func (q *Queries) ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Nickname,
			&i.Role,
			&i.Suspended,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportStatus = `-- name: UpdateReportStatus :one
UPDATE "Report" SET "status" = $2 WHERE "id" = $1 RETURNING id, "userId", "postId", reason, status, "createdAt"
`

type UpdateReportStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error) {
	row := q.db.QueryRow(ctx, updateReportStatus, arg.ID, arg.Status)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
