// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: airuns.sql

package store

import (
	"context"
	"time"
)

const completeAiRun = `-- name: CompleteAiRun :exec
UPDATE "AiRun" SET "status" = 'COMPLETED', "result" = $2, "steps" = $3, "finishedAt" = $4, "updatedAt" = $4 WHERE "id" = $1
`

type CompleteAiRunParams struct {
	ID         string
	Result     []byte
	Steps      []byte
	FinishedAt *time.Time
}

func (q *Queries) CompleteAiRun(ctx context.Context, arg CompleteAiRunParams) error {
	_, err := q.db.Exec(ctx, completeAiRun,
		arg.ID,
		arg.Result,
		arg.Steps,
		arg.FinishedAt,
	)
	return err
}

const createAiRun = `-- name: CreateAiRun :exec
INSERT INTO "AiRun" ("id", "userId", "requestId", "kind", "inputHash", "skillVersion", "model", "status", "steps", "startedAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, 'RUNNING', '[]', $8, $8)
`

type CreateAiRunParams struct {
	ID           string
	UserID       string
	RequestID    string
	Kind         string
	InputHash    string
	SkillVersion string
	Model        string
	StartedAt    time.Time
}

func (q *Queries) CreateAiRun(ctx context.Context, arg CreateAiRunParams) error {
	_, err := q.db.Exec(ctx, createAiRun,
		arg.ID,
		arg.UserID,
		arg.RequestID,
		arg.Kind,
		arg.InputHash,
		arg.SkillVersion,
		arg.Model,
		arg.StartedAt,
	)
	return err
}

const expireStaleRuns = `-- name: ExpireStaleRuns :exec
UPDATE "AiRun" SET "status" = 'INTERRUPTED', "error" = $1, "errorStatus" = 409, "finishedAt" = $2, "updatedAt" = $2
WHERE "userId" = $3 AND "status" = 'RUNNING' AND "updatedAt" < $4
`

type ExpireStaleRunsParams struct {
	Error       *string
	Now         *time.Time
	UserID      string
	StaleBefore time.Time
}

func (q *Queries) ExpireStaleRuns(ctx context.Context, arg ExpireStaleRunsParams) error {
	_, err := q.db.Exec(ctx, expireStaleRuns,
		arg.Error,
		arg.Now,
		arg.UserID,
		arg.StaleBefore,
	)
	return err
}

const failAiRun = `-- name: FailAiRun :execrows
UPDATE "AiRun" SET "status" = 'FAILED', "error" = $2, "errorStatus" = $3, "finishedAt" = $4, "updatedAt" = $4 WHERE "id" = $1 AND "status" = 'RUNNING'
`

type FailAiRunParams struct {
	ID          string
	Error       *string
	ErrorStatus *int32
	FinishedAt  *time.Time
}

func (q *Queries) FailAiRun(ctx context.Context, arg FailAiRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, failAiRun,
		arg.ID,
		arg.Error,
		arg.ErrorStatus,
		arg.FinishedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAiRun = `-- name: GetAiRun :one
SELECT id, "userId", "requestId", kind, "inputHash", "skillVersion", model, status, result, steps, error, "errorStatus", "startedAt", "updatedAt", "finishedAt" FROM "AiRun" WHERE "userId" = $1 AND "requestId" = $2
`

type GetAiRunParams struct {
	UserID    string
	RequestID string
}

func (q *Queries) GetAiRun(ctx context.Context, arg GetAiRunParams) (AiRun, error) {
	row := q.db.QueryRow(ctx, getAiRun, arg.UserID, arg.RequestID)
	var i AiRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.Kind,
		&i.InputHash,
		&i.SkillVersion,
		&i.Model,
		&i.Status,
		&i.Result,
		&i.Steps,
		&i.Error,
		&i.ErrorStatus,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const interruptAiRun = `-- name: InterruptAiRun :execrows
UPDATE "AiRun" SET "status" = 'INTERRUPTED', "error" = $2, "errorStatus" = 503, "finishedAt" = $3, "updatedAt" = $3 WHERE "id" = $1 AND "status" = 'RUNNING'
`

type InterruptAiRunParams struct {
	ID         string
	Error      *string
	FinishedAt *time.Time
}

// A run cut short by this instance's shutdown: the device learns on its next poll, with a retry hint.
func (q *Queries) InterruptAiRun(ctx context.Context, arg InterruptAiRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, interruptAiRun, arg.ID, arg.Error, arg.FinishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockAiRun = `-- name: LockAiRun :one
SELECT id, "userId", "requestId", kind, "inputHash", "skillVersion", model, status, result, steps, error, "errorStatus", "startedAt", "updatedAt", "finishedAt" FROM "AiRun" WHERE "id" = $1 FOR UPDATE
`

func (q *Queries) LockAiRun(ctx context.Context, id string) (AiRun, error) {
	row := q.db.QueryRow(ctx, lockAiRun, id)
	var i AiRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.Kind,
		&i.InputHash,
		&i.SkillVersion,
		&i.Model,
		&i.Status,
		&i.Result,
		&i.Steps,
		&i.Error,
		&i.ErrorStatus,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateAiRunSteps = `-- name: UpdateAiRunSteps :execrows
UPDATE "AiRun" SET "steps" = $2, "updatedAt" = $3 WHERE "id" = $1 AND "status" = 'RUNNING'
`

type UpdateAiRunStepsParams struct {
	ID        string
	Steps     []byte
	UpdatedAt time.Time
}

func (q *Queries) UpdateAiRunSteps(ctx context.Context, arg UpdateAiRunStepsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAiRunSteps, arg.ID, arg.Steps, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
