// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bootstrap.sql

package store

import (
	"context"
	"time"
)

const listAttempts = `-- name: ListAttempts :many
SELECT id, "userId", "questionId", "essayId", answer, correct, score, "createdAt" FROM "Attempt" WHERE "userId" = $1 ORDER BY "createdAt" DESC LIMIT 1000
`

func (q *Queries) ListAttempts(ctx context.Context, userid string) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listAttempts, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attempt{}
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuestionID,
			&i.EssayID,
			&i.Answer,
			&i.Correct,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsWithReviewCount = `-- name: ListCardsWithReviewCount :many
SELECT c.id, c."userId", c."subjectId", c.front, c.back, c.type, c.bucket, c."consecutiveEasy", c."nextReviewAt", c.deleted, c.image, c.masks, c."sourceQuestionId", c.fsrs, c."createdAt", c."materialId", (SELECT count(*) FROM "CardReview" AS r WHERE r."cardId" = c."id")::int AS review_count
FROM "Card" AS c JOIN "Subject" AS s ON s."id" = c."subjectId"
WHERE c."userId" = $1 AND s."deleted" = false ORDER BY c."createdAt" ASC
`

type ListCardsWithReviewCountRow struct {
	ID               string
	UserID           string
	SubjectID        string
	Front            string
	Back             string
	Type             CardType
	Bucket           Bucket
	ConsecutiveEasy  int32
	NextReviewAt     time.Time
	Deleted          bool
	Image            *string
	Masks            []byte
	SourceQuestionID *string
	Fsrs             []byte
	CreatedAt        time.Time
	MaterialID       *string
	ReviewCount      int32
}

func (q *Queries) ListCardsWithReviewCount(ctx context.Context, userid string) ([]ListCardsWithReviewCountRow, error) {
	rows, err := q.db.Query(ctx, listCardsWithReviewCount, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCardsWithReviewCountRow{}
	for rows.Next() {
		var i ListCardsWithReviewCountRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubjectID,
			&i.Front,
			&i.Back,
			&i.Type,
			&i.Bucket,
			&i.ConsecutiveEasy,
			&i.NextReviewAt,
			&i.Deleted,
			&i.Image,
			&i.Masks,
			&i.SourceQuestionID,
			&i.Fsrs,
			&i.CreatedAt,
			&i.MaterialID,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheersReceived = `-- name: ListCheersReceived :many
SELECT c.id, c."senderId", c."recipientId", c.message, c.points, c.thanked, c."createdAt", u."nickname" AS sender_name FROM "Cheer" AS c JOIN "User" AS u ON u."id" = c."senderId"
WHERE c."recipientId" = $1 ORDER BY c."createdAt" DESC LIMIT 100
`

type ListCheersReceivedRow struct {
	ID          string
	SenderID    string
	RecipientID string
	Message     string
	Points      int32
	Thanked     bool
	CreatedAt   time.Time
	SenderName  string
}

func (q *Queries) ListCheersReceived(ctx context.Context, recipientid string) ([]ListCheersReceivedRow, error) {
	rows, err := q.db.Query(ctx, listCheersReceived, recipientid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheersReceivedRow{}
	for rows.Next() {
		var i ListCheersReceivedRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.Message,
			&i.Points,
			&i.Thanked,
			&i.CreatedAt,
			&i.SenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheersSent = `-- name: ListCheersSent :many
SELECT c.id, c."senderId", c."recipientId", c.message, c.points, c.thanked, c."createdAt", u."nickname" AS sender_name FROM "Cheer" AS c JOIN "User" AS u ON u."id" = c."senderId"
WHERE c."senderId" = $1 ORDER BY c."createdAt" DESC LIMIT 100
`

type ListCheersSentRow struct {
	ID          string
	SenderID    string
	RecipientID string
	Message     string
	Points      int32
	Thanked     bool
	CreatedAt   time.Time
	SenderName  string
}

func (q *Queries) ListCheersSent(ctx context.Context, senderid string) ([]ListCheersSentRow, error) {
	rows, err := q.db.Query(ctx, listCheersSent, senderid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheersSentRow{}
	for rows.Next() {
		var i ListCheersSentRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.Message,
			&i.Points,
			&i.Thanked,
			&i.CreatedAt,
			&i.SenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEssays = `-- name: ListEssays :many
SELECT e.id, e."userId", e."subjectId", e."materialId", e.prompt, e.keywords, e.distractors, e."modelAnswer", e.citation FROM "Essay" AS e JOIN "Subject" AS s ON s."id" = e."subjectId" WHERE e."userId" = $1 AND s."deleted" = false
`

func (q *Queries) ListEssays(ctx context.Context, userid string) ([]Essay, error) {
	rows, err := q.db.Query(ctx, listEssays, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Essay{}
	for rows.Next() {
		var i Essay
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubjectID,
			&i.MaterialID,
			&i.Prompt,
			&i.Keywords,
			&i.Distractors,
			&i.ModelAnswer,
			&i.Citation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialsWithUpload = `-- name: ListMaterialsWithUpload :many
SELECT m.id, m."userId", m."subjectId", m.title, m.content, m.type, m.url, m."uploadId", m."pageBreaks", m.extraction, m."createdAt", m."contentHash", m.excerpt, u."pages" AS upload_pages,
  (SELECT count(*) FROM "UploadImage" AS i WHERE i."uploadId" = u."id")::int AS image_count
FROM "Material" AS m JOIN "Subject" AS s ON s."id" = m."subjectId" LEFT JOIN "Upload" AS u ON u."id" = m."uploadId"
WHERE m."userId" = $1 AND s."deleted" = false ORDER BY m."createdAt" DESC
`

type ListMaterialsWithUploadRow struct {
	ID          string
	UserID      string
	SubjectID   string
	Title       string
	Content     string
	Type        string
	Url         *string
	UploadID    *string
	PageBreaks  []int32
	Extraction  *string
	CreatedAt   time.Time
	ContentHash string
	Excerpt     string
	UploadPages *int32
	ImageCount  int32
}

func (q *Queries) ListMaterialsWithUpload(ctx context.Context, userid string) ([]ListMaterialsWithUploadRow, error) {
	rows, err := q.db.Query(ctx, listMaterialsWithUpload, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaterialsWithUploadRow{}
	for rows.Next() {
		var i ListMaterialsWithUploadRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubjectID,
			&i.Title,
			&i.Content,
			&i.Type,
			&i.Url,
			&i.UploadID,
			&i.PageBreaks,
			&i.Extraction,
			&i.CreatedAt,
			&i.ContentHash,
			&i.Excerpt,
			&i.UploadPages,
			&i.ImageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, "userId", title, body, read, href, "createdAt" FROM "Notification" WHERE "userId" = $1 ORDER BY "createdAt" DESC LIMIT 100
`

func (q *Queries) ListNotifications(ctx context.Context, userid string) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.Read,
			&i.Href,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
SELECT q.id, q."userId", q."subjectId", q."materialId", q.prompt, q.options, q.answer, q.explanation, q.citation, q.past, q.future FROM "Question" AS q JOIN "Subject" AS s ON s."id" = q."subjectId" WHERE q."userId" = $1 AND s."deleted" = false
`

func (q *Queries) ListQuestions(ctx context.Context, userid string) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestions, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubjectID,
			&i.MaterialID,
			&i.Prompt,
			&i.Options,
			&i.Answer,
			&i.Explanation,
			&i.Citation,
			&i.Past,
			&i.Future,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCardReviews = `-- name: ListRecentCardReviews :many
SELECT "createdAt" FROM "CardReview" WHERE "userId" = $1 AND "createdAt" >= $2 ORDER BY "createdAt" DESC
`

type ListRecentCardReviewsParams struct {
	UserID    string
	CreatedAt time.Time
}

func (q *Queries) ListRecentCardReviews(ctx context.Context, arg ListRecentCardReviewsParams) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, listRecentCardReviews, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var createdAt time.Time
		if err := rows.Scan(&createdAt); err != nil {
			return nil, err
		}
		items = append(items, createdAt)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, "userId", title, date, start, "end", kind, "subjectId", done, "createdAt" FROM "Schedule" WHERE "userId" = $1 ORDER BY "date" ASC, "start" ASC
`

func (q *Queries) ListSchedules(ctx context.Context, userid string) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedules, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Date,
			&i.Start,
			&i.End,
			&i.Kind,
			&i.SubjectID,
			&i.Done,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectsWithCounts = `-- name: ListSubjectsWithCounts :many
SELECT s.id, s."userId", s.name, s.icon, s.semester, s.color, s."examName", s."examDate", s.deleted, s."createdAt",
  (SELECT count(*) FROM "Material" AS m WHERE m."subjectId" = s."id")::int AS material_count,
  (SELECT count(*) FROM "Question" AS q WHERE q."subjectId" = s."id")::int AS question_count,
  (SELECT count(*) FROM "Card" AS c WHERE c."subjectId" = s."id" AND c."deleted" = false)::int AS card_count
FROM "Subject" AS s WHERE s."userId" = $1 AND s."deleted" = false ORDER BY s."createdAt" ASC
`

type ListSubjectsWithCountsRow struct {
	ID            string
	UserID        string
	Name          string
	Icon          string
	Semester      string
	Color         string
	ExamName      *string
	ExamDate      *string
	Deleted       bool
	CreatedAt     time.Time
	MaterialCount int32
	QuestionCount int32
	CardCount     int32
}

func (q *Queries) ListSubjectsWithCounts(ctx context.Context, userid string) ([]ListSubjectsWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listSubjectsWithCounts, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubjectsWithCountsRow{}
	for rows.Next() {
		var i ListSubjectsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.Semester,
			&i.Color,
			&i.ExamName,
			&i.ExamDate,
			&i.Deleted,
			&i.CreatedAt,
			&i.MaterialCount,
			&i.QuestionCount,
			&i.CardCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const studiedDays = `-- name: StudiedDays :many
SELECT DISTINCT to_char(a."createdAt" AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')::text AS day FROM "Attempt" AS a WHERE a."userId" = $1
UNION
SELECT DISTINCT to_char(r."createdAt" AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')::text AS day FROM "CardReview" AS r WHERE r."userId" = $1
`

func (q *Queries) StudiedDays(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, studiedDays, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var day string
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
