// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package store

import (
	"context"
	"time"
)

const createCard = `-- name: CreateCard :one
INSERT INTO "Card" ("id", "userId", "subjectId", "front", "back", "type", "image", "masks")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, "userId", "subjectId", front, back, type, bucket, "consecutiveEasy", "nextReviewAt", deleted, image, masks, "sourceQuestionId", fsrs, "createdAt", "materialId", "sourceKind", diagram, "maskedNodeIds", "sourceDiagramId"
`

type CreateCardParams struct {
	ID        string
	UserID    string
	SubjectID string
	Front     string
	Back      string
	Type      CardType
	Image     *string
	Masks     []byte
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.ID,
		arg.UserID,
		arg.SubjectID,
		arg.Front,
		arg.Back,
		arg.Type,
		arg.Image,
		arg.Masks,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Front,
		&i.Back,
		&i.Type,
		&i.Bucket,
		&i.ConsecutiveEasy,
		&i.NextReviewAt,
		&i.Deleted,
		&i.Image,
		&i.Masks,
		&i.SourceQuestionID,
		&i.Fsrs,
		&i.CreatedAt,
		&i.MaterialID,
		&i.SourceKind,
		&i.Diagram,
		&i.MaskedNodeIds,
		&i.SourceDiagramId,
	)
	return i, err
}

const createCardReview = `-- name: CreateCardReview :exec
INSERT INTO "CardReview" ("id", "userId", "cardId", "rating", "result", "createdAt") VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateCardReviewParams struct {
	ID        string
	UserID    string
	CardID    string
	Rating    string
	Result    []byte
	CreatedAt time.Time
}

func (q *Queries) CreateCardReview(ctx context.Context, arg CreateCardReviewParams) error {
	_, err := q.db.Exec(ctx, createCardReview,
		arg.ID,
		arg.UserID,
		arg.CardID,
		arg.Rating,
		arg.Result,
		arg.CreatedAt,
	)
	return err
}

const getCardReview = `-- name: GetCardReview :one
SELECT id, "userId", "cardId", rating, result, "createdAt" FROM "CardReview" WHERE "id" = $1
`

func (q *Queries) GetCardReview(ctx context.Context, id string) (CardReview, error) {
	row := q.db.QueryRow(ctx, getCardReview, id)
	var i CardReview
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.Rating,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getOwnedCard = `-- name: GetOwnedCard :one
SELECT c.id, c."userId", c."subjectId", c.front, c.back, c.type, c.bucket, c."consecutiveEasy", c."nextReviewAt", c.deleted, c.image, c.masks, c."sourceQuestionId", c.fsrs, c."createdAt", c."materialId", c."sourceKind", c.diagram, c."maskedNodeIds", c."sourceDiagramId" FROM "Card" AS c JOIN "Subject" AS s ON s."id" = c."subjectId"
WHERE c."id" = $1 AND c."userId" = $2 AND s."deleted" = false
`

type GetOwnedCardParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetOwnedCard(ctx context.Context, arg GetOwnedCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, getOwnedCard, arg.ID, arg.UserID)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Front,
		&i.Back,
		&i.Type,
		&i.Bucket,
		&i.ConsecutiveEasy,
		&i.NextReviewAt,
		&i.Deleted,
		&i.Image,
		&i.Masks,
		&i.SourceQuestionID,
		&i.Fsrs,
		&i.CreatedAt,
		&i.MaterialID,
		&i.SourceKind,
		&i.Diagram,
		&i.MaskedNodeIds,
		&i.SourceDiagramId,
	)
	return i, err
}

const getOwnedImageUpload = `-- name: GetOwnedImageUpload :one
SELECT "id" FROM "Upload" WHERE "id" = $1 AND "userId" = $2 AND "mime" LIKE 'image/%'
`

type GetOwnedImageUploadParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetOwnedImageUpload(ctx context.Context, arg GetOwnedImageUploadParams) (string, error) {
	row := q.db.QueryRow(ctx, getOwnedImageUpload, arg.ID, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getOwnedLiveCard = `-- name: GetOwnedLiveCard :one
SELECT c.id, c."userId", c."subjectId", c.front, c.back, c.type, c.bucket, c."consecutiveEasy", c."nextReviewAt", c.deleted, c.image, c.masks, c."sourceQuestionId", c.fsrs, c."createdAt", c."materialId", c."sourceKind", c.diagram, c."maskedNodeIds", c."sourceDiagramId" FROM "Card" AS c JOIN "Subject" AS s ON s."id" = c."subjectId"
WHERE c."id" = $1 AND c."userId" = $2 AND c."deleted" = false AND s."deleted" = false
`

type GetOwnedLiveCardParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetOwnedLiveCard(ctx context.Context, arg GetOwnedLiveCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, getOwnedLiveCard, arg.ID, arg.UserID)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Front,
		&i.Back,
		&i.Type,
		&i.Bucket,
		&i.ConsecutiveEasy,
		&i.NextReviewAt,
		&i.Deleted,
		&i.Image,
		&i.Masks,
		&i.SourceQuestionID,
		&i.Fsrs,
		&i.CreatedAt,
		&i.MaterialID,
		&i.SourceKind,
		&i.Diagram,
		&i.MaskedNodeIds,
		&i.SourceDiagramId,
	)
	return i, err
}

const getUserPrefs = `-- name: GetUserPrefs :one
SELECT "srsMode", "desiredRetention" FROM "User" WHERE "id" = $1
`

type GetUserPrefsRow struct {
	SrsMode          string
	DesiredRetention float64
}

func (q *Queries) GetUserPrefs(ctx context.Context, id string) (GetUserPrefsRow, error) {
	row := q.db.QueryRow(ctx, getUserPrefs, id)
	var i GetUserPrefsRow
	err := row.Scan(&i.SrsMode, &i.DesiredRetention)
	return i, err
}

const lastCardReviewAt = `-- name: LastCardReviewAt :one
SELECT "createdAt" FROM "CardReview" WHERE "cardId" = $1 AND "userId" = $2 ORDER BY "createdAt" DESC LIMIT 1
`

type LastCardReviewAtParams struct {
	CardID string
	UserID string
}

func (q *Queries) LastCardReviewAt(ctx context.Context, arg LastCardReviewAtParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, lastCardReviewAt, arg.CardID, arg.UserID)
	var createdAt time.Time
	err := row.Scan(&createdAt)
	return createdAt, err
}

const listWrongQuestions = `-- name: ListWrongQuestions :many
SELECT q.id, q."userId", q."subjectId", q."materialId", q.prompt, q.options, q.answer, q.explanation, q.citation, q.past, q.future, q."learningExplanation" FROM "Question" AS q JOIN "Subject" AS s ON s."id" = q."subjectId"
WHERE q."id" = ANY($1::text[]) AND q."userId" = $2 AND s."deleted" = false
  AND EXISTS (SELECT 1 FROM "Attempt" AS a WHERE a."questionId" = q."id" AND a."userId" = $2 AND a."correct" = false)
`

type ListWrongQuestionsParams struct {
	Ids    []string
	UserID string
}

func (q *Queries) ListWrongQuestions(ctx context.Context, arg ListWrongQuestionsParams) ([]Question, error) {
	rows, err := q.db.Query(ctx, listWrongQuestions, arg.Ids, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubjectID,
			&i.MaterialID,
			&i.Prompt,
			&i.Options,
			&i.Answer,
			&i.Explanation,
			&i.Citation,
			&i.Past,
			&i.Future,
			&i.LearningExplanation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardFields = `-- name: UpdateCardFields :one
UPDATE "Card" SET
  "deleted" = COALESCE($1::bool, "deleted"),
  "front" = COALESCE($2::text, "front"),
  "back" = COALESCE($3::text, "back")
WHERE "id" = $4 RETURNING id, "userId", "subjectId", front, back, type, bucket, "consecutiveEasy", "nextReviewAt", deleted, image, masks, "sourceQuestionId", fsrs, "createdAt", "materialId", "sourceKind", diagram, "maskedNodeIds", "sourceDiagramId"
`

type UpdateCardFieldsParams struct {
	Deleted *bool
	Front   *string
	Back    *string
	ID      string
}

func (q *Queries) UpdateCardFields(ctx context.Context, arg UpdateCardFieldsParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCardFields,
		arg.Deleted,
		arg.Front,
		arg.Back,
		arg.ID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Front,
		&i.Back,
		&i.Type,
		&i.Bucket,
		&i.ConsecutiveEasy,
		&i.NextReviewAt,
		&i.Deleted,
		&i.Image,
		&i.Masks,
		&i.SourceQuestionID,
		&i.Fsrs,
		&i.CreatedAt,
		&i.MaterialID,
		&i.SourceKind,
		&i.Diagram,
		&i.MaskedNodeIds,
		&i.SourceDiagramId,
	)
	return i, err
}

const updateCardSchedule = `-- name: UpdateCardSchedule :one
UPDATE "Card" SET "bucket" = $2, "consecutiveEasy" = $3, "nextReviewAt" = $4, "fsrs" = $5 WHERE "id" = $1 RETURNING id, "userId", "subjectId", front, back, type, bucket, "consecutiveEasy", "nextReviewAt", deleted, image, masks, "sourceQuestionId", fsrs, "createdAt", "materialId", "sourceKind", diagram, "maskedNodeIds", "sourceDiagramId"
`

type UpdateCardScheduleParams struct {
	ID              string
	Bucket          Bucket
	ConsecutiveEasy int32
	NextReviewAt    time.Time
	Fsrs            []byte
}

func (q *Queries) UpdateCardSchedule(ctx context.Context, arg UpdateCardScheduleParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCardSchedule,
		arg.ID,
		arg.Bucket,
		arg.ConsecutiveEasy,
		arg.NextReviewAt,
		arg.Fsrs,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Front,
		&i.Back,
		&i.Type,
		&i.Bucket,
		&i.ConsecutiveEasy,
		&i.NextReviewAt,
		&i.Deleted,
		&i.Image,
		&i.Masks,
		&i.SourceQuestionID,
		&i.Fsrs,
		&i.CreatedAt,
		&i.MaterialID,
		&i.SourceKind,
		&i.Diagram,
		&i.MaskedNodeIds,
		&i.SourceDiagramId,
	)
	return i, err
}

const upsertWrongNoteCard = `-- name: UpsertWrongNoteCard :one
INSERT INTO "Card" ("id", "userId", "subjectId", "front", "back", "sourceQuestionId")
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT ("userId", "sourceQuestionId", "sourceKind") DO UPDATE SET "deleted" = false
RETURNING id, "userId", "subjectId", front, back, type, bucket, "consecutiveEasy", "nextReviewAt", deleted, image, masks, "sourceQuestionId", fsrs, "createdAt", "materialId", "sourceKind", diagram, "maskedNodeIds", "sourceDiagramId"
`

type UpsertWrongNoteCardParams struct {
	ID               string
	UserID           string
	SubjectID        string
	Front            string
	Back             string
	SourceQuestionID *string
}

func (q *Queries) UpsertWrongNoteCard(ctx context.Context, arg UpsertWrongNoteCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, upsertWrongNoteCard,
		arg.ID,
		arg.UserID,
		arg.SubjectID,
		arg.Front,
		arg.Back,
		arg.SourceQuestionID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Front,
		&i.Back,
		&i.Type,
		&i.Bucket,
		&i.ConsecutiveEasy,
		&i.NextReviewAt,
		&i.Deleted,
		&i.Image,
		&i.Masks,
		&i.SourceQuestionID,
		&i.Fsrs,
		&i.CreatedAt,
		&i.MaterialID,
		&i.SourceKind,
		&i.Diagram,
		&i.MaskedNodeIds,
		&i.SourceDiagramId,
	)
	return i, err
}
