// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: community.sql

package store

import (
	"context"
)

const createBlock = `-- name: CreateBlock :exec
INSERT INTO "Block" ("userId", "blockedId") VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type CreateBlockParams struct {
	UserID    string
	BlockedID string
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) error {
	_, err := q.db.Exec(ctx, createBlock, arg.UserID, arg.BlockedID)
	return err
}

const createComment = `-- name: CreateComment :one
INSERT INTO "Comment" ("id", "postId", "userId", "body", "parentId")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, "postId", "userId", body, "parentId", "createdAt"
`

type CreateCommentParams struct {
	ID       string
	PostID   string
	UserID   string
	Body     string
	ParentID *string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.PostID,
		arg.UserID,
		arg.Body,
		arg.ParentID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Body,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO "Post" ("id", "userId", "role", "category", "title", "body", "anonymous", "school")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, "userId", role, category, title, body, anonymous, "createdAt", school
`

type CreatePostParams struct {
	ID        string
	UserID    string
	Role      Role
	Category  string
	Title     string
	Body      string
	Anonymous bool
	School    string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.UserID,
		arg.Role,
		arg.Category,
		arg.Title,
		arg.Body,
		arg.Anonymous,
		arg.School,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Category,
		&i.Title,
		&i.Body,
		&i.Anonymous,
		&i.CreatedAt,
		&i.School,
	)
	return i, err
}

const createPostLike = `-- name: CreatePostLike :exec
INSERT INTO "PostLike" ("userId", "postId") VALUES ($1, $2)
`

type CreatePostLikeParams struct {
	UserID string
	PostID string
}

func (q *Queries) CreatePostLike(ctx context.Context, arg CreatePostLikeParams) error {
	_, err := q.db.Exec(ctx, createPostLike, arg.UserID, arg.PostID)
	return err
}

const createPostSave = `-- name: CreatePostSave :exec
INSERT INTO "PostSave" ("userId", "postId") VALUES ($1, $2)
`

type CreatePostSaveParams struct {
	UserID string
	PostID string
}

func (q *Queries) CreatePostSave(ctx context.Context, arg CreatePostSaveParams) error {
	_, err := q.db.Exec(ctx, createPostSave, arg.UserID, arg.PostID)
	return err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM "Block" WHERE "userId" = $1 AND "blockedId" = $2
`

type DeleteBlockParams struct {
	UserID    string
	BlockedID string
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.Exec(ctx, deleteBlock, arg.UserID, arg.BlockedID)
	return err
}

const deletePostLike = `-- name: DeletePostLike :exec
DELETE FROM "PostLike" WHERE "userId" = $1 AND "postId" = $2
`

type DeletePostLikeParams struct {
	UserID string
	PostID string
}

func (q *Queries) DeletePostLike(ctx context.Context, arg DeletePostLikeParams) error {
	_, err := q.db.Exec(ctx, deletePostLike, arg.UserID, arg.PostID)
	return err
}

const deletePostSave = `-- name: DeletePostSave :exec
DELETE FROM "PostSave" WHERE "userId" = $1 AND "postId" = $2
`

type DeletePostSaveParams struct {
	UserID string
	PostID string
}

func (q *Queries) DeletePostSave(ctx context.Context, arg DeletePostSaveParams) error {
	_, err := q.db.Exec(ctx, deletePostSave, arg.UserID, arg.PostID)
	return err
}

const getPeer = `-- name: GetPeer :one
SELECT u.id, u.name, u.nickname, u.role, u.school, u.grade, u.streak, u.points, u.suspended, u."selectedChildId", u."srsMode", u."desiredRetention", u.privacy, u."completedSubjects", u."linkFailures", u."linkLockedUntil", u."createdAt",
  EXISTS (
    SELECT 1 FROM "Block" AS b
    WHERE (b."userId" = $1::text AND b."blockedId" = u."id")
       OR (b."userId" = u."id" AND b."blockedId" = $1::text)
  ) AS blocked
FROM "User" AS u
WHERE u."id" = $2
`

type GetPeerParams struct {
	ViewerID string
	UserID   string
}

type GetPeerRow struct {
	User    User
	Blocked bool
}

// A user with whether a block stands between them and the viewer in either direction.
func (q *Queries) GetPeer(ctx context.Context, arg GetPeerParams) (GetPeerRow, error) {
	row := q.db.QueryRow(ctx, getPeer, arg.ViewerID, arg.UserID)
	var i GetPeerRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Name,
		&i.User.Nickname,
		&i.User.Role,
		&i.User.School,
		&i.User.Grade,
		&i.User.Streak,
		&i.User.Points,
		&i.User.Suspended,
		&i.User.SelectedChildID,
		&i.User.SrsMode,
		&i.User.DesiredRetention,
		&i.User.Privacy,
		&i.User.CompletedSubjects,
		&i.User.LinkFailures,
		&i.User.LinkLockedUntil,
		&i.User.CreatedAt,
		&i.Blocked,
	)
	return i, err
}

const getPostAccess = `-- name: GetPostAccess :one

SELECT p.id, p."userId", p.role, p.category, p.title, p.body, p.anonymous, p."createdAt", p.school, u."suspended" AS author_suspended,
  EXISTS (
    SELECT 1 FROM "Block" AS b
    WHERE (b."userId" = $1::text AND b."blockedId" = p."userId")
       OR (b."userId" = p."userId" AND b."blockedId" = $1::text)
  ) AS blocked
FROM "Post" AS p JOIN "User" AS u ON u."id" = p."userId"
WHERE p."id" = $2
`

type GetPostAccessParams struct {
	ViewerID string
	PostID   string
}

type GetPostAccessRow struct {
	Post            Post
	AuthorSuspended bool
	Blocked         bool
}

// Community: posts, likes, saves, comments, reports and blocks (api.ts posts/reports/blocks,
// bootstrap.ts postsFor).
// The post with what accessiblePost() decides on: the author's suspension and whether a block
// stands between the viewer and the author in either direction.
func (q *Queries) GetPostAccess(ctx context.Context, arg GetPostAccessParams) (GetPostAccessRow, error) {
	row := q.db.QueryRow(ctx, getPostAccess, arg.ViewerID, arg.PostID)
	var i GetPostAccessRow
	err := row.Scan(
		&i.Post.ID,
		&i.Post.UserID,
		&i.Post.Role,
		&i.Post.Category,
		&i.Post.Title,
		&i.Post.Body,
		&i.Post.Anonymous,
		&i.Post.CreatedAt,
		&i.Post.School,
		&i.AuthorSuspended,
		&i.Blocked,
	)
	return i, err
}

const hasPostLike = `-- name: HasPostLike :one
SELECT EXISTS (SELECT 1 FROM "PostLike" WHERE "userId" = $1 AND "postId" = $2)
`

type HasPostLikeParams struct {
	UserID string
	PostID string
}

func (q *Queries) HasPostLike(ctx context.Context, arg HasPostLikeParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPostLike, arg.UserID, arg.PostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasPostSave = `-- name: HasPostSave :one
SELECT EXISTS (SELECT 1 FROM "PostSave" WHERE "userId" = $1 AND "postId" = $2)
`

type HasPostSaveParams struct {
	UserID string
	PostID string
}

func (q *Queries) HasPostSave(ctx context.Context, arg HasPostSaveParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPostSave, arg.UserID, arg.PostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isTopLevelComment = `-- name: IsTopLevelComment :one
SELECT EXISTS (SELECT 1 FROM "Comment" WHERE "id" = $1 AND "postId" = $2 AND "parentId" IS NULL)
`

type IsTopLevelCommentParams struct {
	ID     string
	PostID string
}

// Replies go one level deep: a parent must be a top-level comment of the same post.
func (q *Queries) IsTopLevelComment(ctx context.Context, arg IsTopLevelCommentParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTopLevelComment, arg.ID, arg.PostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listComments = `-- name: ListComments :many
SELECT c.id, c."postId", c."userId", c.body, c."parentId", c."createdAt", u."nickname" AS author_nickname
FROM "Comment" AS c JOIN "User" AS u ON u."id" = c."userId"
WHERE c."postId" = $1
  AND u."suspended" = false
  AND NOT EXISTS (
    SELECT 1 FROM "Block" AS b
    WHERE (b."userId" = $2::text AND b."blockedId" = c."userId")
       OR (b."userId" = c."userId" AND b."blockedId" = $2::text)
  )
ORDER BY c."createdAt" ASC
LIMIT 500
`

type ListCommentsParams struct {
	PostID   string
	ViewerID string
}

type ListCommentsRow struct {
	Comment        Comment
	AuthorNickname string
}

// The 500 oldest comments of a post, hiding those by suspended authors and by anyone the viewer
// blocked or was blocked by.
func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments, arg.PostID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsRow{}
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.Comment.ID,
			&i.Comment.PostID,
			&i.Comment.UserID,
			&i.Comment.Body,
			&i.Comment.ParentID,
			&i.Comment.CreatedAt,
			&i.AuthorNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT p.id, p."userId", p.role, p.category, p.title, p.body, p.anonymous, p."createdAt", p.school, u."nickname" AS author_nickname,
  (SELECT count(*) FROM "PostLike" AS l WHERE l."postId" = p."id") AS likes,
  EXISTS (SELECT 1 FROM "PostLike" AS l WHERE l."postId" = p."id" AND l."userId" = $1::text) AS liked,
  EXISTS (SELECT 1 FROM "PostSave" AS s WHERE s."postId" = p."id" AND s."userId" = $1::text) AS saved,
  (SELECT count(*) FROM "Comment" AS c WHERE c."postId" = p."id") AS comment_count
FROM "Post" AS p JOIN "User" AS u ON u."id" = p."userId"
WHERE p."role" = $2
  AND NOT EXISTS (SELECT 1 FROM "CommunityPost" cp WHERE cp."postId"=p."id" AND cp."deleted")
  AND (NOT $3::boolean OR (NOT p."anonymous" AND EXISTS (SELECT 1 FROM "Follow" f WHERE f."followerId" = $1::text AND f."followingId"=p."userId")))
  AND ($4::text = '' OR (p."userId" = $1::text AND EXISTS(SELECT 1 FROM "CommunityPost" cp WHERE cp."postId"=p."id" AND cp."sourceRef"->>'questionId' = $4::text)))
  AND ($5::text = '' OR EXISTS (SELECT 1 FROM "CommunityPost" cp WHERE cp."postId"=p."id" AND (cp."tags"->>'subjectId' = $5::text OR cp."tags"->>'subjectName' = (SELECT "name" FROM "Subject" WHERE "id" = $5::text AND "userId" = $1::text AND NOT "deleted"))))
  AND (NOT $6::boolean OR (p."category"='질문' AND p."createdAt" < now()-interval '24 hours' AND NOT EXISTS(SELECT 1 FROM "Comment" c WHERE c."postId"=p."id") AND EXISTS(SELECT 1 FROM "CommunityPost" cp JOIN "Subject" sub ON sub."userId" = $1::text AND NOT sub."deleted" AND sub."name"=cp."tags"->>'subjectName' WHERE cp."postId"=p."id")))
  AND (p."school" = $7::text OR ($8::boolean AND (p."school" = '' OR p."school" = $7::text)))
  AND (NOT $9::boolean OR p."userId" = $1::text)
  AND (NOT $10::boolean OR EXISTS (SELECT 1 FROM "PostSave" AS ps WHERE ps."postId" = p."id" AND ps."userId" = $1::text))
  AND u."suspended" = false
  AND NOT EXISTS (
    SELECT 1 FROM "Block" AS b
    WHERE (b."userId" = $1::text AND b."blockedId" = p."userId")
       OR (b."userId" = p."userId" AND b."blockedId" = $1::text)
  )
  AND (NOT $11::boolean OR EXISTS (SELECT 1 FROM "Comment" AS c WHERE c."postId" = p."id" AND c."userId" = $1::text))
ORDER BY p."createdAt" DESC
LIMIT 100
`

type ListPostsParams struct {
	ViewerID      string
	Role          Role
	FollowingOnly bool
	QuestionID    string
	SubjectID     string
	Unanswered    bool
	School        string
	Activity      bool
	Mine          bool
	SavedOnly     bool
	Commented     bool
}

type ListPostsRow struct {
	Post           Post
	AuthorNickname string
	Likes          int64
	Liked          bool
	Saved          bool
	CommentCount   int64
}

// The community feed: the 100 newest posts of one role, minus those by suspended authors and by
// anyone the viewer blocked or was blocked by; commented keeps only the posts the viewer commented on.
func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts,
		arg.ViewerID,
		arg.Role,
		arg.FollowingOnly,
		arg.QuestionID,
		arg.SubjectID,
		arg.Unanswered,
		arg.School,
		arg.Activity,
		arg.Mine,
		arg.SavedOnly,
		arg.Commented,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsRow{}
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.UserID,
			&i.Post.Role,
			&i.Post.Category,
			&i.Post.Title,
			&i.Post.Body,
			&i.Post.Anonymous,
			&i.Post.CreatedAt,
			&i.Post.School,
			&i.AuthorNickname,
			&i.Likes,
			&i.Liked,
			&i.Saved,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReport = `-- name: UpsertReport :one
INSERT INTO "Report" ("id", "userId", "postId", "reason")
VALUES ($1, $2, $3, $4)
ON CONFLICT ("userId", "postId") DO UPDATE SET "reason" = EXCLUDED."reason", "status" = 'OPEN'
RETURNING id, "userId", "postId", reason, status, "createdAt"
`

type UpsertReportParams struct {
	ID     string
	UserID string
	PostID string
	Reason string
}

// One report per (user, post): reporting again replaces the reason and reopens it.
func (q *Queries) UpsertReport(ctx context.Context, arg UpsertReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, upsertReport,
		arg.ID,
		arg.UserID,
		arg.PostID,
		arg.Reason,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
