// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core.sql

package store

import (
	"context"
)

const getOwnedSubject = `-- name: GetOwnedSubject :one
SELECT id, "userId", name, icon, semester, color, "examName", "examDate", deleted, "createdAt" FROM "Subject" WHERE "id" = $1 AND "userId" = $2 AND "deleted" = false
`

type GetOwnedSubjectParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetOwnedSubject(ctx context.Context, arg GetOwnedSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, getOwnedSubject, arg.ID, arg.UserID)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Semester,
		&i.Color,
		&i.ExamName,
		&i.ExamDate,
		&i.Deleted,
		&i.CreatedAt,
	)
	return i, err
}

const selectedChild = `-- name: SelectedChild :one
SELECT u.id, u.name, u.nickname, u.role, u.school, u.grade, u.streak, u.points, u.suspended, u."selectedChildId", u."srsMode", u."desiredRetention", u.privacy, u."completedSubjects", u."linkFailures", u."linkLockedUntil", u."createdAt" FROM "ParentLink" AS l JOIN "User" AS u ON u."id" = l."studentId"
WHERE l."parentId" = $1 AND ($2::text = '' OR l."studentId" = $2::text)
ORDER BY l."createdAt" ASC
LIMIT 1
`

type SelectedChildParams struct {
	ParentID   string
	SelectedID string
}

func (q *Queries) SelectedChild(ctx context.Context, arg SelectedChildParams) (User, error) {
	row := q.db.QueryRow(ctx, selectedChild, arg.ParentID, arg.SelectedID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Role,
		&i.School,
		&i.Grade,
		&i.Streak,
		&i.Points,
		&i.Suspended,
		&i.SelectedChildID,
		&i.SrsMode,
		&i.DesiredRetention,
		&i.Privacy,
		&i.CompletedSubjects,
		&i.LinkFailures,
		&i.LinkLockedUntil,
		&i.CreatedAt,
	)
	return i, err
}
