// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: materials.sql

package store

import (
	"context"
)

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO "Material" ("id", "userId", "subjectId", "title", "content", "type", "url", "uploadId", "pageBreaks", "extraction", "contentHash", "excerpt")
VALUES ($1, $2, $3, $4, $10, $5, $6, $7, $8, $9,
  encode(sha256(convert_to($10, 'UTF8')), 'hex'), left(btrim(regexp_replace($10, '\s+', ' ', 'g')), 160))
RETURNING id, "userId", "subjectId", title, content, type, url, "uploadId", "pageBreaks", extraction, "createdAt", "contentHash", excerpt
`

type CreateMaterialParams struct {
	ID         string
	UserID     string
	SubjectID  string
	Title      string
	Type       string
	Url        *string
	UploadID   *string
	PageBreaks []int32
	Extraction *string
	Content    string
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, createMaterial,
		arg.ID,
		arg.UserID,
		arg.SubjectID,
		arg.Title,
		arg.Type,
		arg.Url,
		arg.UploadID,
		arg.PageBreaks,
		arg.Extraction,
		arg.Content,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Title,
		&i.Content,
		&i.Type,
		&i.Url,
		&i.UploadID,
		&i.PageBreaks,
		&i.Extraction,
		&i.CreatedAt,
		&i.ContentHash,
		&i.Excerpt,
	)
	return i, err
}

const deleteMaterial = `-- name: DeleteMaterial :exec
DELETE FROM "Material" WHERE "id" = $1
`

func (q *Queries) DeleteMaterial(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMaterial, id)
	return err
}

const getMaterialContent = `-- name: GetMaterialContent :one
SELECT "content", "subjectId" FROM "Material" AS m JOIN "Subject" AS s ON s."id" = m."subjectId"
WHERE m."id" = $1 AND m."userId" = $2 AND s."deleted" = false
`

type GetMaterialContentParams struct {
	ID     string
	UserID string
}

type GetMaterialContentRow struct {
	Content   string
	SubjectID string
}

func (q *Queries) GetMaterialContent(ctx context.Context, arg GetMaterialContentParams) (GetMaterialContentRow, error) {
	row := q.db.QueryRow(ctx, getMaterialContent, arg.ID, arg.UserID)
	var i GetMaterialContentRow
	err := row.Scan(&i.Content, &i.SubjectID)
	return i, err
}

const getOwnedMaterial = `-- name: GetOwnedMaterial :one
SELECT m.id, m."userId", m."subjectId", m.title, m.content, m.type, m.url, m."uploadId", m."pageBreaks", m.extraction, m."createdAt", m."contentHash", m.excerpt FROM "Material" AS m JOIN "Subject" AS s ON s."id" = m."subjectId"
WHERE m."id" = $1 AND m."userId" = $2 AND s."deleted" = false
`

type GetOwnedMaterialParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetOwnedMaterial(ctx context.Context, arg GetOwnedMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, getOwnedMaterial, arg.ID, arg.UserID)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Title,
		&i.Content,
		&i.Type,
		&i.Url,
		&i.UploadID,
		&i.PageBreaks,
		&i.Extraction,
		&i.CreatedAt,
		&i.ContentHash,
		&i.Excerpt,
	)
	return i, err
}

const getOwnedSampleMaterial = `-- name: GetOwnedSampleMaterial :one
SELECT m.id, m."userId", m."subjectId", m.title, m.content, m.type, m.url, m."uploadId", m."pageBreaks", m.extraction, m."createdAt", m."contentHash", m.excerpt FROM "Material" AS m JOIN "Subject" AS s ON s."id" = m."subjectId"
WHERE m."userId" = $1 AND m."extraction" = 'sample' AND s."deleted" = false
ORDER BY m."createdAt" DESC LIMIT 1
`

// The sample chapter is marked by its extraction value, never matched by title (a learner may
// have a material of their own with the same title).
func (q *Queries) GetOwnedSampleMaterial(ctx context.Context, userid string) (Material, error) {
	row := q.db.QueryRow(ctx, getOwnedSampleMaterial, userid)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Title,
		&i.Content,
		&i.Type,
		&i.Url,
		&i.UploadID,
		&i.PageBreaks,
		&i.Extraction,
		&i.CreatedAt,
		&i.ContentHash,
		&i.Excerpt,
	)
	return i, err
}

const getOwnedUploadWithMaterial = `-- name: GetOwnedUploadWithMaterial :one
SELECT u."id", u."mime", u."pages", u."pageBreaks", u."extraction", u."textHash", m."id" AS material_id
FROM "Upload" AS u LEFT JOIN "Material" AS m ON m."uploadId" = u."id"
WHERE u."id" = $1 AND u."userId" = $2
`

type GetOwnedUploadWithMaterialParams struct {
	ID     string
	UserID string
}

type GetOwnedUploadWithMaterialRow struct {
	ID         string
	Mime       string
	Pages      *int32
	PageBreaks []int32
	Extraction *string
	TextHash   *string
	MaterialID *string
}

func (q *Queries) GetOwnedUploadWithMaterial(ctx context.Context, arg GetOwnedUploadWithMaterialParams) (GetOwnedUploadWithMaterialRow, error) {
	row := q.db.QueryRow(ctx, getOwnedUploadWithMaterial, arg.ID, arg.UserID)
	var i GetOwnedUploadWithMaterialRow
	err := row.Scan(
		&i.ID,
		&i.Mime,
		&i.Pages,
		&i.PageBreaks,
		&i.Extraction,
		&i.TextHash,
		&i.MaterialID,
	)
	return i, err
}

const getUploadMeta = `-- name: GetUploadMeta :one
SELECT "id", "userId", "mime", "name", "size", "sha256", "pages", "pageBreaks", "extraction", "textHash", "createdAt" FROM "Upload" WHERE "id" = $1
`

func (q *Queries) GetUploadMeta(ctx context.Context, id string) (Upload, error) {
	row := q.db.QueryRow(ctx, getUploadMeta, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Mime,
		&i.Name,
		&i.Size,
		&i.Sha256,
		&i.Pages,
		&i.PageBreaks,
		&i.Extraction,
		&i.TextHash,
		&i.CreatedAt,
	)
	return i, err
}

const listUploadImages = `-- name: ListUploadImages :many
SELECT "id", "page", "order", "paragraph", "anchor", "x", "y", "w", "h", "width", "height", "mime", "context"
FROM "UploadImage" WHERE "uploadId" = $1 ORDER BY "page" ASC, "order" ASC
`

type ListUploadImagesRow struct {
	ID        string
	Page      int32
	Order     int32
	Paragraph int32
	Anchor    int32
	X         float64
	Y         float64
	W         float64
	H         float64
	Width     int32
	Height    int32
	Mime      string
	Context   string
}

func (q *Queries) ListUploadImages(ctx context.Context, uploadid string) ([]ListUploadImagesRow, error) {
	rows, err := q.db.Query(ctx, listUploadImages, uploadid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUploadImagesRow{}
	for rows.Next() {
		var i ListUploadImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Page,
			&i.Order,
			&i.Paragraph,
			&i.Anchor,
			&i.X,
			&i.Y,
			&i.W,
			&i.H,
			&i.Width,
			&i.Height,
			&i.Mime,
			&i.Context,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaterial = `-- name: UpdateMaterial :one
UPDATE "Material" SET
  "title" = COALESCE($1::text, "title"),
  "content" = COALESCE($2::text, "content"),
  "contentHash" = CASE WHEN $2::text IS NULL THEN "contentHash" ELSE encode(sha256(convert_to($2::text, 'UTF8')), 'hex') END,
  "excerpt" = CASE WHEN $2::text IS NULL THEN "excerpt" ELSE left(btrim(regexp_replace($2::text, '\s+', ' ', 'g')), 160) END,
  "pageBreaks" = CASE WHEN $3::bool THEN $4::int[] ELSE "pageBreaks" END,
  "extraction" = CASE WHEN $3::bool THEN $5::text ELSE "extraction" END
WHERE "id" = $6 RETURNING id, "userId", "subjectId", title, content, type, url, "uploadId", "pageBreaks", extraction, "createdAt", "contentHash", excerpt
`

type UpdateMaterialParams struct {
	Title      *string
	Content    *string
	SetPages   bool
	PageBreaks []int32
	Extraction *string
	ID         string
}

func (q *Queries) UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, updateMaterial,
		arg.Title,
		arg.Content,
		arg.SetPages,
		arg.PageBreaks,
		arg.Extraction,
		arg.ID,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Title,
		&i.Content,
		&i.Type,
		&i.Url,
		&i.UploadID,
		&i.PageBreaks,
		&i.Extraction,
		&i.CreatedAt,
		&i.ContentHash,
		&i.Excerpt,
	)
	return i, err
}
