// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Bucket string

const (
	BucketAGAIN    Bucket = "AGAIN"
	BucketHARD     Bucket = "HARD"
	BucketGOOD     Bucket = "GOOD"
	BucketEASY     Bucket = "EASY"
	BucketMASTERED Bucket = "MASTERED"
)

func (e *Bucket) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Bucket(s)
	case string:
		*e = Bucket(s)
	default:
		return fmt.Errorf("unsupported scan type for Bucket: %T", src)
	}
	return nil
}

type NullBucket struct {
	Bucket Bucket
	Valid  bool // Valid is true if Bucket is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBucket) Scan(value interface{}) error {
	if value == nil {
		ns.Bucket, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Bucket.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBucket) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Bucket), nil
}

type CardType string

const (
	CardTypeCONCEPT    CardType = "CONCEPT"
	CardTypeRELATION   CardType = "RELATION"
	CardTypeCOMPARISON CardType = "COMPARISON"
	CardTypeBLIND      CardType = "BLIND"
)

func (e *CardType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CardType(s)
	case string:
		*e = CardType(s)
	default:
		return fmt.Errorf("unsupported scan type for CardType: %T", src)
	}
	return nil
}

type NullCardType struct {
	CardType CardType
	Valid    bool // Valid is true if CardType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCardType) Scan(value interface{}) error {
	if value == nil {
		ns.CardType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CardType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCardType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CardType), nil
}

type Role string

const (
	RoleSTUDENT Role = "STUDENT"
	RolePARENT  Role = "PARENT"
	RoleADMIN   Role = "ADMIN"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type ScheduleKind string

const (
	ScheduleKindFIXED    ScheduleKind = "FIXED"
	ScheduleKindFLEXIBLE ScheduleKind = "FLEXIBLE"
)

func (e *ScheduleKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScheduleKind(s)
	case string:
		*e = ScheduleKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ScheduleKind: %T", src)
	}
	return nil
}

type NullScheduleKind struct {
	ScheduleKind ScheduleKind
	Valid        bool // Valid is true if ScheduleKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScheduleKind) Scan(value interface{}) error {
	if value == nil {
		ns.ScheduleKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScheduleKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScheduleKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScheduleKind), nil
}

type AiRun struct {
	ID           string
	UserID       string
	RequestID    string
	Kind         string
	InputHash    string
	SkillVersion string
	Model        string
	Status       string
	Result       []byte
	Steps        []byte
	Error        *string
	ErrorStatus  *int32
	StartedAt    time.Time
	UpdatedAt    time.Time
	FinishedAt   *time.Time
}

type Attempt struct {
	ID               string
	UserID           string
	QuestionID       *string
	EssayID          *string
	Answer           string
	Correct          bool
	Score            int32
	CreatedAt        time.Time
	ResponseMs       *int32
	BeatsSeen        int32
	ExplainDepth     *string
	MicroResult      *string
	DivergenceNodeId *string
	RequestID        *string
}

type Block struct {
	UserID    string
	BlockedID string
}

type Card struct {
	ID               string
	UserID           string
	SubjectID        string
	Front            string
	Back             string
	Type             CardType
	Bucket           Bucket
	ConsecutiveEasy  int32
	NextReviewAt     time.Time
	Deleted          bool
	Image            *string
	Masks            []byte
	SourceQuestionID *string
	Fsrs             []byte
	CreatedAt        time.Time
	MaterialID       *string
	SourceKind       string
	Diagram          []byte
	MaskedNodeIds    []string
	SourceDiagramId  *string
}

type CardReview struct {
	ID        string
	UserID    string
	CardID    string
	Rating    string
	Result    []byte
	CreatedAt time.Time
}

type Cheer struct {
	ID          string
	SenderID    string
	RecipientID string
	Message     string
	Points      int32
	Thanked     bool
	CreatedAt   time.Time
}

type Comment struct {
	ID        string
	PostID    string
	UserID    string
	Body      string
	ParentID  *string
	CreatedAt time.Time
}

type CommunityAction struct {
	UserID    string
	PostID    string
	BlockId   string
	Kind      string
	Result    []byte
	CreatedAt time.Time
}

type CommunityCard struct {
	CardID string
	Public bool
}

type CommunityCardClone struct {
	UserID       string
	SourceCardId string
	CardID       string
}

type CommunityComment struct {
	CommentId string
	Block     []byte
	RequestID *string
	UserID    string
}

type CommunityFollowEvent struct {
	ID        string
	UserID    string
	CreatedAt time.Time
}

type CommunityPost struct {
	PostID            string
	Blocks            []byte
	Tags              []byte
	SourceRef         []byte
	RequestID         *string
	UserID            string
	Deleted           bool
	EditedAt          *time.Time
	SolvedAt          *time.Time
	AcceptedCommentId *string
}

type CommunityPrivacy struct {
	UserID     string
	Visibility []byte
}

type CommunityReward struct {
	PostID    string
	UserID    string
	CreatedAt time.Time
}

type CommunitySavedQuestion struct {
	UserID     string
	QuestionID string
	PostID     string
}

type Essay struct {
	ID          string
	UserID      string
	SubjectID   string
	MaterialID  string
	Prompt      string
	Keywords    []string
	Distractors []string
	ModelAnswer string
	Citation    string
}

type ExplanationReport struct {
	ID         string
	UserID     string
	QuestionID string
	NodeId     string
	Reason     string
	CreatedAt  time.Time
}

type Follow struct {
	FollowerID  string
	FollowingID string
}

type Invite struct {
	Code      string
	StudentID string
	ExpiresAt time.Time
}

type Material struct {
	ID          string
	UserID      string
	SubjectID   string
	Title       string
	Content     string
	Type        string
	Url         *string
	UploadID    *string
	PageBreaks  []int32
	Extraction  *string
	CreatedAt   time.Time
	ContentHash string
	Excerpt     string
}

type Message struct {
	ID          string
	SenderID    string
	RecipientID string
	Body        string
	CreatedAt   time.Time
}

type Notification struct {
	ID        string
	UserID    string
	Title     string
	Body      string
	Read      bool
	Href      string
	CreatedAt time.Time
}

type OAuthAccount struct {
	ID         string
	Provider   string
	ProviderID string
	UserID     string
}

type OpsBlob struct {
	Key         string
	ContentType string
	Size        int64
	Data        []byte
	CreatedAt   pgtype.Timestamptz
}

type ParentLink struct {
	ParentID  string
	StudentID string
	CreatedAt time.Time
}

type Post struct {
	ID        string
	UserID    string
	Role      Role
	Category  string
	Title     string
	Body      string
	Anonymous bool
	CreatedAt time.Time
	School    string
}

type PostLike struct {
	UserID string
	PostID string
}

type PostSave struct {
	UserID string
	PostID string
}

type Question struct {
	ID                  string
	UserID              string
	SubjectID           string
	MaterialID          string
	Prompt              string
	Options             []string
	Answer              int32
	Explanation         string
	Citation            string
	Past                string
	Future              string
	LearningExplanation []byte
}

type Report struct {
	ID        string
	UserID    string
	PostID    string
	Reason    string
	Status    string
	CreatedAt time.Time
}

type Schedule struct {
	ID        string
	UserID    string
	Title     string
	Date      string
	Start     string
	End       string
	Kind      ScheduleKind
	SubjectID *string
	Done      bool
	CreatedAt time.Time
}

type School struct {
	ID   string
	Name string
}

type Session struct {
	ID        string
	UserID    string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Subject struct {
	ID        string
	UserID    string
	Name      string
	Icon      string
	Semester  string
	Color     string
	ExamName  *string
	ExamDate  *string
	Deleted   bool
	CreatedAt time.Time
}

type Upload struct {
	ID         string
	UserID     string
	Mime       string
	Name       string
	Size       int32
	Sha256     *string
	Pages      *int32
	PageBreaks []int32
	Extraction *string
	TextHash   *string
	CreatedAt  time.Time
}

type UploadImage struct {
	ID        string
	UploadID  string
	Page      int32
	Order     int32
	Paragraph int32
	Anchor    int32
	X         float64
	Y         float64
	W         float64
	H         float64
	Width     int32
	Height    int32
	Mime      string
	Context   string
}

type User struct {
	ID                string
	Name              string
	Nickname          string
	Role              Role
	School            string
	Grade             string
	Streak            int32
	Points            int32
	Suspended         bool
	SelectedChildID   *string
	SrsMode           string
	DesiredRetention  float64
	Privacy           []byte
	CompletedSubjects []string
	LinkFailures      int32
	LinkLockedUntil   *time.Time
	CreatedAt         time.Time
}
