// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package store

import (
	"context"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :exec
INSERT INTO "OAuthAccount" ("id", "provider", "providerId", "userId") VALUES ($1, $2, $3, $4)
`

type CreateOAuthAccountParams struct {
	ID         string
	Provider   string
	ProviderID string
	UserID     string
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) error {
	_, err := q.db.Exec(ctx, createOAuthAccount,
		arg.ID,
		arg.Provider,
		arg.ProviderID,
		arg.UserID,
	)
	return err
}

const getOAuthAccountUser = `-- name: GetOAuthAccountUser :one
SELECT a."id" AS account_id, u.id, u.name, u.nickname, u.role, u.school, u.grade, u.streak, u.points, u.suspended, u."selectedChildId", u."srsMode", u."desiredRetention", u.privacy, u."completedSubjects", u."linkFailures", u."linkLockedUntil", u."createdAt"
FROM "OAuthAccount" AS a JOIN "User" AS u ON u."id" = a."userId"
WHERE a."provider" = $1 AND a."providerId" = $2
`

type GetOAuthAccountUserParams struct {
	Provider   string
	ProviderID string
}

type GetOAuthAccountUserRow struct {
	AccountID string
	User      User
}

func (q *Queries) GetOAuthAccountUser(ctx context.Context, arg GetOAuthAccountUserParams) (GetOAuthAccountUserRow, error) {
	row := q.db.QueryRow(ctx, getOAuthAccountUser, arg.Provider, arg.ProviderID)
	var i GetOAuthAccountUserRow
	err := row.Scan(
		&i.AccountID,
		&i.User.ID,
		&i.User.Name,
		&i.User.Nickname,
		&i.User.Role,
		&i.User.School,
		&i.User.Grade,
		&i.User.Streak,
		&i.User.Points,
		&i.User.Suspended,
		&i.User.SelectedChildID,
		&i.User.SrsMode,
		&i.User.DesiredRetention,
		&i.User.Privacy,
		&i.User.CompletedSubjects,
		&i.User.LinkFailures,
		&i.User.LinkLockedUntil,
		&i.User.CreatedAt,
	)
	return i, err
}
