// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parent.sql

package store

import (
	"context"
	"time"
)

const addPoints = `-- name: AddPoints :exec
UPDATE "User" SET "points" = "points" + $2 WHERE "id" = $1
`

type AddPointsParams struct {
	ID     string
	Points int32
}

func (q *Queries) AddPoints(ctx context.Context, arg AddPointsParams) error {
	_, err := q.db.Exec(ctx, addPoints, arg.ID, arg.Points)
	return err
}

const consumeInvite = `-- name: ConsumeInvite :execrows
DELETE FROM "Invite" WHERE "code" = $1 AND "expiresAt" > $2
`

type ConsumeInviteParams struct {
	Code string
	Now  time.Time
}

func (q *Queries) ConsumeInvite(ctx context.Context, arg ConsumeInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeInvite, arg.Code, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countMasteredCards = `-- name: CountMasteredCards :one
SELECT count(*) FROM "Card" AS c JOIN "Subject" AS s ON s."id" = c."subjectId"
WHERE c."userId" = $1 AND c."bucket" = 'MASTERED' AND c."deleted" = false AND s."deleted" = false
`

func (q *Queries) CountMasteredCards(ctx context.Context, userid string) (int64, error) {
	row := q.db.QueryRow(ctx, countMasteredCards, userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudyDaysSince = `-- name: CountStudyDaysSince :one
SELECT count(DISTINCT d.day) FROM (
    SELECT to_char((a."createdAt" AT TIME ZONE 'UTC') AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD') AS day
    FROM "Attempt" AS a WHERE a."userId" = $1::text AND a."createdAt" >= $2::timestamp
    UNION ALL
    SELECT to_char((r."createdAt" AT TIME ZONE 'UTC') AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD') AS day
    FROM "CardReview" AS r WHERE r."userId" = $1::text AND r."createdAt" >= $2::timestamp
) AS d
`

type CountStudyDaysSinceParams struct {
	UserID string
	Since  time.Time
}

// Distinct Seoul calendar dates with an attempt or a card review since @since (stored timestamps are UTC).
func (q *Queries) CountStudyDaysSince(ctx context.Context, arg CountStudyDaysSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudyDaysSince, arg.UserID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWeeklyQuestions = `-- name: CountWeeklyQuestions :one
SELECT count(*) FROM "Attempt" WHERE "userId" = $1 AND "createdAt" >= $2 AND "questionId" IS NOT NULL
`

type CountWeeklyQuestionsParams struct {
	UserID string
	Since  time.Time
}

func (q *Queries) CountWeeklyQuestions(ctx context.Context, arg CountWeeklyQuestionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWeeklyQuestions, arg.UserID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCheer = `-- name: CreateCheer :one
INSERT INTO "Cheer" ("id", "senderId", "recipientId", "message", "points") VALUES ($1, $2, $3, $4, $5) RETURNING id, "senderId", "recipientId", message, points, thanked, "createdAt"
`

type CreateCheerParams struct {
	ID          string
	SenderID    string
	RecipientID string
	Message     string
	Points      int32
}

func (q *Queries) CreateCheer(ctx context.Context, arg CreateCheerParams) (Cheer, error) {
	row := q.db.QueryRow(ctx, createCheer,
		arg.ID,
		arg.SenderID,
		arg.RecipientID,
		arg.Message,
		arg.Points,
	)
	var i Cheer
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Message,
		&i.Points,
		&i.Thanked,
		&i.CreatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO "Invite" ("code", "studentId", "expiresAt") VALUES ($1, $2, $3)
`

type CreateInviteParams struct {
	Code      string
	StudentID string
	ExpiresAt time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite, arg.Code, arg.StudentID, arg.ExpiresAt)
	return err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO "Notification" ("id", "userId", "title", "body", "href") VALUES ($1, $2, $3, $4, $5)
`

type CreateNotificationParams struct {
	ID     string
	UserID string
	Title  string
	Body   string
	Href   string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.Href,
	)
	return err
}

const deleteParentLink = `-- name: DeleteParentLink :exec
DELETE FROM "ParentLink" WHERE "parentId" = $1 AND "studentId" = $2
`

type DeleteParentLinkParams struct {
	ParentID  string
	StudentID string
}

func (q *Queries) DeleteParentLink(ctx context.Context, arg DeleteParentLinkParams) error {
	_, err := q.db.Exec(ctx, deleteParentLink, arg.ParentID, arg.StudentID)
	return err
}

const getInviteStudent = `-- name: GetInviteStudent :one
SELECT i.code, i."studentId", i."expiresAt", u.id, u.name, u.nickname, u.role, u.school, u.grade, u.streak, u.points, u.suspended, u."selectedChildId", u."srsMode", u."desiredRetention", u.privacy, u."completedSubjects", u."linkFailures", u."linkLockedUntil", u."createdAt"
FROM "Invite" AS i JOIN "User" AS u ON u."id" = i."studentId"
WHERE i."code" = $1
`

type GetInviteStudentRow struct {
	Invite Invite
	User   User
}

func (q *Queries) GetInviteStudent(ctx context.Context, code string) (GetInviteStudentRow, error) {
	row := q.db.QueryRow(ctx, getInviteStudent, code)
	var i GetInviteStudentRow
	err := row.Scan(
		&i.Invite.Code,
		&i.Invite.StudentID,
		&i.Invite.ExpiresAt,
		&i.User.ID,
		&i.User.Name,
		&i.User.Nickname,
		&i.User.Role,
		&i.User.School,
		&i.User.Grade,
		&i.User.Streak,
		&i.User.Points,
		&i.User.Suspended,
		&i.User.SelectedChildID,
		&i.User.SrsMode,
		&i.User.DesiredRetention,
		&i.User.Privacy,
		&i.User.CompletedSubjects,
		&i.User.LinkFailures,
		&i.User.LinkLockedUntil,
		&i.User.CreatedAt,
	)
	return i, err
}

const getParentLink = `-- name: GetParentLink :one
SELECT "parentId", "studentId", "createdAt" FROM "ParentLink" WHERE "parentId" = $1 AND "studentId" = $2
`

type GetParentLinkParams struct {
	ParentID  string
	StudentID string
}

func (q *Queries) GetParentLink(ctx context.Context, arg GetParentLinkParams) (ParentLink, error) {
	row := q.db.QueryRow(ctx, getParentLink, arg.ParentID, arg.StudentID)
	var i ParentLink
	err := row.Scan(&i.ParentID, &i.StudentID, &i.CreatedAt)
	return i, err
}

const inviteCodeExists = `-- name: InviteCodeExists :one
SELECT EXISTS (SELECT 1 FROM "Invite" WHERE "code" = $1)
`

func (q *Queries) InviteCodeExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, inviteCodeExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const linkSucceeded = `-- name: LinkSucceeded :exec
UPDATE "User" SET "linkFailures" = 0, "linkLockedUntil" = NULL, "selectedChildId" = $2 WHERE "id" = $1
`

type LinkSucceededParams struct {
	ID              string
	SelectedChildID *string
}

func (q *Queries) LinkSucceeded(ctx context.Context, arg LinkSucceededParams) error {
	_, err := q.db.Exec(ctx, linkSucceeded, arg.ID, arg.SelectedChildID)
	return err
}

const listChildren = `-- name: ListChildren :many
SELECT u.id, u.name, u.nickname, u.role, u.school, u.grade, u.streak, u.points, u.suspended, u."selectedChildId", u."srsMode", u."desiredRetention", u.privacy, u."completedSubjects", u."linkFailures", u."linkLockedUntil", u."createdAt" FROM "ParentLink" AS l JOIN "User" AS u ON u."id" = l."studentId"
WHERE l."parentId" = $1
ORDER BY l."createdAt" ASC
`

func (q *Queries) ListChildren(ctx context.Context, parentid string) ([]User, error) {
	rows, err := q.db.Query(ctx, listChildren, parentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Nickname,
			&i.Role,
			&i.School,
			&i.Grade,
			&i.Streak,
			&i.Points,
			&i.Suspended,
			&i.SelectedChildID,
			&i.SrsMode,
			&i.DesiredRetention,
			&i.Privacy,
			&i.CompletedSubjects,
			&i.LinkFailures,
			&i.LinkLockedUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLinkState = `-- name: SetLinkState :exec
UPDATE "User" SET "linkFailures" = $2, "linkLockedUntil" = $3 WHERE "id" = $1
`

type SetLinkStateParams struct {
	ID              string
	LinkFailures    int32
	LinkLockedUntil *time.Time
}

func (q *Queries) SetLinkState(ctx context.Context, arg SetLinkStateParams) error {
	_, err := q.db.Exec(ctx, setLinkState, arg.ID, arg.LinkFailures, arg.LinkLockedUntil)
	return err
}

const subjectAttemptStats = `-- name: SubjectAttemptStats :many
SELECT s."id", s."name",
    count(a."id")::int AS count,
    (count(a."id") FILTER (WHERE a."correct"))::int AS correct
FROM "Subject" AS s
LEFT JOIN "Question" AS q ON q."subjectId" = s."id"
LEFT JOIN "Attempt" AS a ON a."questionId" = q."id" AND a."userId" = $1
WHERE s."userId" = $1 AND s."deleted" = false
GROUP BY s."id", s."name", s."createdAt"
ORDER BY s."createdAt" ASC, s."id" ASC
`

type SubjectAttemptStatsRow struct {
	ID      string
	Name    string
	Count   int32
	Correct int32
}

// Every live subject of the student with the student's attempts on that subject's questions.
func (q *Queries) SubjectAttemptStats(ctx context.Context, userID string) ([]SubjectAttemptStatsRow, error) {
	rows, err := q.db.Query(ctx, subjectAttemptStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubjectAttemptStatsRow{}
	for rows.Next() {
		var i SubjectAttemptStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Count,
			&i.Correct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sweepInvites = `-- name: SweepInvites :exec
DELETE FROM "Invite" WHERE "studentId" = $1 OR "expiresAt" < $2
`

type SweepInvitesParams struct {
	StudentID string
	Now       time.Time
}

// A student's earlier codes and everyone's expired ones go before a new code is issued.
func (q *Queries) SweepInvites(ctx context.Context, arg SweepInvitesParams) error {
	_, err := q.db.Exec(ctx, sweepInvites, arg.StudentID, arg.Now)
	return err
}

const thankCheer = `-- name: ThankCheer :execrows
UPDATE "Cheer" SET "thanked" = true WHERE "id" = $1 AND "recipientId" = $2
`

type ThankCheerParams struct {
	ID          string
	RecipientID string
}

func (q *Queries) ThankCheer(ctx context.Context, arg ThankCheerParams) (int64, error) {
	result, err := q.db.Exec(ctx, thankCheer, arg.ID, arg.RecipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertParentLink = `-- name: UpsertParentLink :exec
INSERT INTO "ParentLink" ("parentId", "studentId") VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type UpsertParentLinkParams struct {
	ParentID  string
	StudentID string
}

func (q *Queries) UpsertParentLink(ctx context.Context, arg UpsertParentLinkParams) error {
	_, err := q.db.Exec(ctx, upsertParentLink, arg.ParentID, arg.StudentID)
	return err
}
