// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package store

import (
	"context"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO "Schedule" ("id", "userId", "title", "date", "start", "end", "kind", "subjectId", "done")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, "userId", title, date, start, "end", kind, "subjectId", done, "createdAt"
`

type CreateScheduleParams struct {
	ID        string
	UserID    string
	Title     string
	Date      string
	Start     string
	End       string
	Kind      ScheduleKind
	SubjectID *string
	Done      bool
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Date,
		arg.Start,
		arg.End,
		arg.Kind,
		arg.SubjectID,
		arg.Done,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Date,
		&i.Start,
		&i.End,
		&i.Kind,
		&i.SubjectID,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :execrows
DELETE FROM "Schedule" WHERE "id" = $1 AND "userId" = $2
`

type DeleteScheduleParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSchedule, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOwnedSchedule = `-- name: GetOwnedSchedule :one
SELECT id, "userId", title, date, start, "end", kind, "subjectId", done, "createdAt" FROM "Schedule" WHERE "id" = $1 AND "userId" = $2
`

type GetOwnedScheduleParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetOwnedSchedule(ctx context.Context, arg GetOwnedScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, getOwnedSchedule, arg.ID, arg.UserID)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Date,
		&i.Start,
		&i.End,
		&i.Kind,
		&i.SubjectID,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}

const listSchedulesOnDate = `-- name: ListSchedulesOnDate :many
SELECT id, "userId", title, date, start, "end", kind, "subjectId", done, "createdAt" FROM "Schedule" WHERE "userId" = $1 AND "date" = $2 AND "id" <> $3 ORDER BY "start" ASC
`

type ListSchedulesOnDateParams struct {
	UserID string
	Date   string
	ID     string
}

func (q *Queries) ListSchedulesOnDate(ctx context.Context, arg ListSchedulesOnDateParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesOnDate, arg.UserID, arg.Date, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Date,
			&i.Start,
			&i.End,
			&i.Kind,
			&i.SubjectID,
			&i.Done,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE "Schedule" SET "title" = $2, "date" = $3, "start" = $4, "end" = $5, "kind" = $6, "subjectId" = $7, "done" = $8
WHERE "id" = $1 RETURNING id, "userId", title, date, start, "end", kind, "subjectId", done, "createdAt"
`

type UpdateScheduleParams struct {
	ID        string
	Title     string
	Date      string
	Start     string
	End       string
	Kind      ScheduleKind
	SubjectID *string
	Done      bool
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.ID,
		arg.Title,
		arg.Date,
		arg.Start,
		arg.End,
		arg.Kind,
		arg.SubjectID,
		arg.Done,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Date,
		&i.Start,
		&i.End,
		&i.Kind,
		&i.SubjectID,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}
