// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO "Session" ("id", "userId", "expiresAt") VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	ID        string
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM "Session" WHERE "userId" = $1 AND "expiresAt" < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, userid string) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions, userid)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM "Session" WHERE "id" = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM "Session" WHERE "userId" = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userid string) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userid)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT s."id" AS session_id, s."expiresAt" AS session_expires, s."createdAt" AS session_created, u.id, u.name, u.nickname, u.role, u.school, u.grade, u.streak, u.points, u.suspended, u."selectedChildId", u."srsMode", u."desiredRetention", u.privacy, u."completedSubjects", u."linkFailures", u."linkLockedUntil", u."createdAt"
FROM "Session" AS s JOIN "User" AS u ON u."id" = s."userId"
WHERE s."id" = $1
`

type GetSessionUserRow struct {
	SessionID      string
	SessionExpires time.Time
	SessionCreated time.Time
	User           User
}

func (q *Queries) GetSessionUser(ctx context.Context, id string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, id)
	var i GetSessionUserRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionExpires,
		&i.SessionCreated,
		&i.User.ID,
		&i.User.Name,
		&i.User.Nickname,
		&i.User.Role,
		&i.User.School,
		&i.User.Grade,
		&i.User.Streak,
		&i.User.Points,
		&i.User.Suspended,
		&i.User.SelectedChildID,
		&i.User.SrsMode,
		&i.User.DesiredRetention,
		&i.User.Privacy,
		&i.User.CompletedSubjects,
		&i.User.LinkFailures,
		&i.User.LinkLockedUntil,
		&i.User.CreatedAt,
	)
	return i, err
}

const renewSession = `-- name: RenewSession :one
UPDATE "Session" SET "expiresAt" = GREATEST("expiresAt", $1) WHERE "id" = $2 RETURNING "expiresAt"
`

type RenewSessionParams struct {
	ExpiresAt time.Time
	ID        string
}

// Moves the session's expiry forward, never backwards (concurrent requests may renew together).
func (q *Queries) RenewSession(ctx context.Context, arg RenewSessionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, renewSession, arg.ExpiresAt, arg.ID)
	var expiresAt time.Time
	err := row.Scan(&expiresAt)
	return expiresAt, err
}
