// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package store

import (
	"context"
	"time"
)

const countUserComments = `-- name: CountUserComments :one
SELECT count(*) FROM "Comment" WHERE "userId" = $1
`

func (q *Queries) CountUserComments(ctx context.Context, userid string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserComments, userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserPosts = `-- name: CountUserPosts :one
SELECT count(*) FROM "Post" WHERE "userId" = $1
`

func (q *Queries) CountUserPosts(ctx context.Context, userid string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserPosts, userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFollow = `-- name: CreateFollow :exec
INSERT INTO "Follow" ("followerId", "followingId") VALUES ($1, $2)
`

type CreateFollowParams struct {
	FollowerID  string
	FollowingID string
}

func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) error {
	_, err := q.db.Exec(ctx, createFollow, arg.FollowerID, arg.FollowingID)
	return err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO "Message" ("id", "senderId", "recipientId", "body")
VALUES ($1, $2, $3, $4)
RETURNING id, "senderId", "recipientId", body, "createdAt"
`

type CreateMessageParams struct {
	ID          string
	SenderID    string
	RecipientID string
	Body        string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.SenderID,
		arg.RecipientID,
		arg.Body,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM "Follow" WHERE "followerId" = $1 AND "followingId" = $2
`

type DeleteFollowParams struct {
	FollowerID  string
	FollowingID string
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.Exec(ctx, deleteFollow, arg.FollowerID, arg.FollowingID)
	return err
}

const hasFollow = `-- name: HasFollow :one
SELECT EXISTS (SELECT 1 FROM "Follow" WHERE "followerId" = $1 AND "followingId" = $2)
`

type HasFollowParams struct {
	FollowerID  string
	FollowingID string
}

func (q *Queries) HasFollow(ctx context.Context, arg HasFollowParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasFollow, arg.FollowerID, arg.FollowingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBlocked = `-- name: ListBlocked :many
SELECT u."id", u."nickname"
FROM "Block" AS b JOIN "User" AS u ON u."id" = b."blockedId"
WHERE b."userId" = $1
`

type ListBlockedRow struct {
	ID       string
	Nickname string
}

func (q *Queries) ListBlocked(ctx context.Context, userid string) ([]ListBlockedRow, error) {
	rows, err := q.db.Query(ctx, listBlocked, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlockedRow{}
	for rows.Next() {
		var i ListBlockedRow
		if err := rows.Scan(&i.ID, &i.Nickname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT u."id", u."nickname", recent."body", recent."createdAt"
FROM "User" u
JOIN LATERAL (
  SELECT m."body", m."createdAt" FROM "Message" m
  WHERE (m."senderId" = $1::text AND m."recipientId" = u."id")
     OR (m."recipientId" = $1::text AND m."senderId" = u."id")
  ORDER BY m."createdAt" DESC, m."id" DESC LIMIT 1
) recent ON true
WHERE u."id" <> $1::text AND u."role" = $2 AND NOT u."suspended"
  AND NOT EXISTS (SELECT 1 FROM "Block" b
    WHERE (b."userId" = $1::text AND b."blockedId" = u."id")
       OR (b."userId" = u."id" AND b."blockedId" = $1::text))
ORDER BY recent."createdAt" DESC, u."id" LIMIT 100
`

type ListConversationsParams struct {
	ViewerID string
	Role     Role
}

type ListConversationsRow struct {
	ID        string
	Nickname  string
	Body      string
	CreatedAt time.Time
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.ViewerID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsRow{}
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowers = `-- name: ListFollowers :many

SELECT u."id", u."nickname"
FROM "Follow" AS f JOIN "User" AS u ON u."id" = f."followerId"
WHERE f."followingId" = $1
`

type ListFollowersRow struct {
	ID       string
	Nickname string
}

// Social: the follow graph, direct messages and the school directory (api.ts social/follow/
// messages/schools).
func (q *Queries) ListFollowers(ctx context.Context, followingid string) ([]ListFollowersRow, error) {
	rows, err := q.db.Query(ctx, listFollowers, followingid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersRow{}
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(&i.ID, &i.Nickname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT u."id", u."nickname"
FROM "Follow" AS f JOIN "User" AS u ON u."id" = f."followingId"
WHERE f."followerId" = $1
`

type ListFollowingRow struct {
	ID       string
	Nickname string
}

func (q *Queries) ListFollowing(ctx context.Context, followerid string) ([]ListFollowingRow, error) {
	rows, err := q.db.Query(ctx, listFollowing, followerid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingRow{}
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(&i.ID, &i.Nickname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, "senderId", "recipientId", body, "createdAt" FROM "Message"
WHERE ("senderId" = $1::text AND "recipientId" = $2::text)
   OR ("senderId" = $2::text AND "recipientId" = $1::text)
ORDER BY "createdAt" ASC
LIMIT 200
`

type ListMessagesParams struct {
	UserID string
	PeerID string
}

// The 200 oldest messages between two accounts, in either direction.
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.UserID, arg.PeerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeers = `-- name: ListPeers :many
SELECT u."id", u."nickname"
FROM "User" AS u
WHERE u."role" = $1
  AND u."id" <> $2::text
  AND u."suspended" = false
  AND NOT EXISTS (
    SELECT 1 FROM "Block" AS b
    WHERE (b."userId" = $2::text AND b."blockedId" = u."id")
       OR (b."userId" = u."id" AND b."blockedId" = $2::text)
  )
LIMIT 100
`

type ListPeersParams struct {
	Role     Role
	ViewerID string
}

type ListPeersRow struct {
	ID       string
	Nickname string
}

// Up to 100 accounts of the same role the viewer may talk to: not themselves, not suspended and
// with no block in either direction.
func (q *Queries) ListPeers(ctx context.Context, arg ListPeersParams) ([]ListPeersRow, error) {
	rows, err := q.db.Query(ctx, listPeers, arg.Role, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPeersRow{}
	for rows.Next() {
		var i ListPeersRow
		if err := rows.Scan(&i.ID, &i.Nickname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSchools = `-- name: SearchSchools :many
SELECT id, name FROM "School"
WHERE "name" ILIKE $1::text
ORDER BY "name" ASC
LIMIT 30
`

// pattern is a LIKE pattern the handler builds ('%' + escaped query + '%'); the match ignores case.
func (q *Queries) SearchSchools(ctx context.Context, pattern string) ([]School, error) {
	rows, err := q.db.Query(ctx, searchSchools, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
