// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: study.sql

package store

import (
	"context"
	"time"
)

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO "Attempt" ("id", "userId", "questionId", "essayId", "answer", "correct", "score")
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, "userId", "questionId", "essayId", answer, correct, score, "createdAt"
`

type CreateAttemptParams struct {
	ID         string
	UserID     string
	QuestionID *string
	EssayID    *string
	Answer     string
	Correct    bool
	Score      int32
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.ID,
		arg.UserID,
		arg.QuestionID,
		arg.EssayID,
		arg.Answer,
		arg.Correct,
		arg.Score,
	)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.EssayID,
		&i.Answer,
		&i.Correct,
		&i.Score,
		&i.CreatedAt,
	)
	return i, err
}

const createEssay = `-- name: CreateEssay :one
INSERT INTO "Essay" ("id", "userId", "subjectId", "materialId", "prompt", "keywords", "distractors", "modelAnswer", "citation")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, "userId", "subjectId", "materialId", prompt, keywords, distractors, "modelAnswer", citation
`

type CreateEssayParams struct {
	ID          string
	UserID      string
	SubjectID   string
	MaterialID  string
	Prompt      string
	Keywords    []string
	Distractors []string
	ModelAnswer string
	Citation    string
}

func (q *Queries) CreateEssay(ctx context.Context, arg CreateEssayParams) (Essay, error) {
	row := q.db.QueryRow(ctx, createEssay,
		arg.ID,
		arg.UserID,
		arg.SubjectID,
		arg.MaterialID,
		arg.Prompt,
		arg.Keywords,
		arg.Distractors,
		arg.ModelAnswer,
		arg.Citation,
	)
	var i Essay
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.MaterialID,
		&i.Prompt,
		&i.Keywords,
		&i.Distractors,
		&i.ModelAnswer,
		&i.Citation,
	)
	return i, err
}

const createGeneratedCard = `-- name: CreateGeneratedCard :one
INSERT INTO "Card" ("id", "userId", "subjectId", "front", "back", "type", "materialId") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, "userId", "subjectId", front, back, type, bucket, "consecutiveEasy", "nextReviewAt", deleted, image, masks, "sourceQuestionId", fsrs, "createdAt", "materialId"
`

type CreateGeneratedCardParams struct {
	ID         string
	UserID     string
	SubjectID  string
	Front      string
	Back       string
	Type       CardType
	MaterialID *string
}

func (q *Queries) CreateGeneratedCard(ctx context.Context, arg CreateGeneratedCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createGeneratedCard,
		arg.ID,
		arg.UserID,
		arg.SubjectID,
		arg.Front,
		arg.Back,
		arg.Type,
		arg.MaterialID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Front,
		&i.Back,
		&i.Type,
		&i.Bucket,
		&i.ConsecutiveEasy,
		&i.NextReviewAt,
		&i.Deleted,
		&i.Image,
		&i.Masks,
		&i.SourceQuestionID,
		&i.Fsrs,
		&i.CreatedAt,
		&i.MaterialID,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO "Question" ("id", "userId", "subjectId", "materialId", "prompt", "options", "answer", "explanation", "citation", "past", "future")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, "userId", "subjectId", "materialId", prompt, options, answer, explanation, citation, past, future
`

type CreateQuestionParams struct {
	ID          string
	UserID      string
	SubjectID   string
	MaterialID  string
	Prompt      string
	Options     []string
	Answer      int32
	Explanation string
	Citation    string
	Past        string
	Future      string
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.ID,
		arg.UserID,
		arg.SubjectID,
		arg.MaterialID,
		arg.Prompt,
		arg.Options,
		arg.Answer,
		arg.Explanation,
		arg.Citation,
		arg.Past,
		arg.Future,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.MaterialID,
		&i.Prompt,
		&i.Options,
		&i.Answer,
		&i.Explanation,
		&i.Citation,
		&i.Past,
		&i.Future,
	)
	return i, err
}

const getOwnedEssay = `-- name: GetOwnedEssay :one
SELECT e.id, e."userId", e."subjectId", e."materialId", e.prompt, e.keywords, e.distractors, e."modelAnswer", e.citation FROM "Essay" AS e JOIN "Subject" AS s ON s."id" = e."subjectId"
WHERE e."id" = $1 AND e."userId" = $2 AND s."deleted" = false
`

type GetOwnedEssayParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetOwnedEssay(ctx context.Context, arg GetOwnedEssayParams) (Essay, error) {
	row := q.db.QueryRow(ctx, getOwnedEssay, arg.ID, arg.UserID)
	var i Essay
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.MaterialID,
		&i.Prompt,
		&i.Keywords,
		&i.Distractors,
		&i.ModelAnswer,
		&i.Citation,
	)
	return i, err
}

const getOwnedQuestion = `-- name: GetOwnedQuestion :one
SELECT q.id, q."userId", q."subjectId", q."materialId", q.prompt, q.options, q.answer, q.explanation, q.citation, q.past, q.future FROM "Question" AS q JOIN "Subject" AS s ON s."id" = q."subjectId"
WHERE q."id" = $1 AND q."userId" = $2 AND s."deleted" = false
`

type GetOwnedQuestionParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetOwnedQuestion(ctx context.Context, arg GetOwnedQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, getOwnedQuestion, arg.ID, arg.UserID)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.MaterialID,
		&i.Prompt,
		&i.Options,
		&i.Answer,
		&i.Explanation,
		&i.Citation,
		&i.Past,
		&i.Future,
	)
	return i, err
}

const listLiveCardsForPlanner = `-- name: ListLiveCardsForPlanner :many
SELECT "subjectId", "bucket", "nextReviewAt", "fsrs", "deleted" FROM "Card" WHERE "userId" = $1 AND "deleted" = false
`

type ListLiveCardsForPlannerRow struct {
	SubjectID    string
	Bucket       Bucket
	NextReviewAt time.Time
	Fsrs         []byte
	Deleted      bool
}

func (q *Queries) ListLiveCardsForPlanner(ctx context.Context, userid string) ([]ListLiveCardsForPlannerRow, error) {
	rows, err := q.db.Query(ctx, listLiveCardsForPlanner, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveCardsForPlannerRow{}
	for rows.Next() {
		var i ListLiveCardsForPlannerRow
		if err := rows.Scan(
			&i.SubjectID,
			&i.Bucket,
			&i.NextReviewAt,
			&i.Fsrs,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSubjects = `-- name: ListLiveSubjects :many
SELECT id, "userId", name, icon, semester, color, "examName", "examDate", deleted, "createdAt" FROM "Subject" WHERE "userId" = $1 AND "deleted" = false ORDER BY "createdAt" ASC
`

func (q *Queries) ListLiveSubjects(ctx context.Context, userid string) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listLiveSubjects, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.Semester,
			&i.Color,
			&i.ExamName,
			&i.ExamDate,
			&i.Deleted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
