// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subjects.sql

package store

import (
	"context"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO "Subject" ("id", "userId", "name", "examName", "examDate") VALUES ($1, $2, $3, $4, $5) RETURNING id, "userId", name, icon, semester, color, "examName", "examDate", deleted, "createdAt"
`

type CreateSubjectParams struct {
	ID       string
	UserID   string
	Name     string
	ExamName *string
	ExamDate *string
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ExamName,
		arg.ExamDate,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Semester,
		&i.Color,
		&i.ExamName,
		&i.ExamDate,
		&i.Deleted,
		&i.CreatedAt,
	)
	return i, err
}

const getOwnedSubjectByName = `-- name: GetOwnedSubjectByName :one
SELECT id, "userId", name, icon, semester, color, "examName", "examDate", deleted, "createdAt" FROM "Subject" WHERE "userId" = $1 AND "name" = $2 AND "deleted" = false
ORDER BY "createdAt" ASC LIMIT 1
`

type GetOwnedSubjectByNameParams struct {
	UserID string
	Name   string
}

func (q *Queries) GetOwnedSubjectByName(ctx context.Context, arg GetOwnedSubjectByNameParams) (Subject, error) {
	row := q.db.QueryRow(ctx, getOwnedSubjectByName, arg.UserID, arg.Name)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Semester,
		&i.Color,
		&i.ExamName,
		&i.ExamDate,
		&i.Deleted,
		&i.CreatedAt,
	)
	return i, err
}

const softDeleteSubject = `-- name: SoftDeleteSubject :one
UPDATE "Subject" SET "deleted" = true WHERE "id" = $1 RETURNING id, "userId", name, icon, semester, color, "examName", "examDate", deleted, "createdAt"
`

func (q *Queries) SoftDeleteSubject(ctx context.Context, id string) (Subject, error) {
	row := q.db.QueryRow(ctx, softDeleteSubject, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Semester,
		&i.Color,
		&i.ExamName,
		&i.ExamDate,
		&i.Deleted,
		&i.CreatedAt,
	)
	return i, err
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE "Subject" SET
  "name" = COALESCE($1::text, "name"),
  "examName" = CASE WHEN $2::bool THEN $3::text ELSE "examName" END,
  "examDate" = CASE WHEN $4::bool THEN $5::text ELSE "examDate" END
WHERE "id" = $6 RETURNING id, "userId", name, icon, semester, color, "examName", "examDate", deleted, "createdAt"
`

type UpdateSubjectParams struct {
	Name        *string
	SetExamName bool
	ExamName    *string
	SetExamDate bool
	ExamDate    *string
	ID          string
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, updateSubject,
		arg.Name,
		arg.SetExamName,
		arg.ExamName,
		arg.SetExamDate,
		arg.ExamDate,
		arg.ID,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Semester,
		&i.Color,
		&i.ExamName,
		&i.ExamDate,
		&i.Deleted,
		&i.CreatedAt,
	)
	return i, err
}
