// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sweep.sql

package store

import (
	"context"
	"time"
)

const deleteUploadImagesByUpload = `-- name: DeleteUploadImagesByUpload :execrows
DELETE FROM "UploadImage" WHERE "uploadId" = ANY($1::text[])
`

func (q *Queries) DeleteUploadImagesByUpload(ctx context.Context, ids []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUploadImagesByUpload, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUploadsByID = `-- name: DeleteUploadsByID :execrows
DELETE FROM "Upload" WHERE "id" = ANY($1::text[])
`

func (q *Queries) DeleteUploadsByID(ctx context.Context, ids []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUploadsByID, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSweepableUploads = `-- name: ListSweepableUploads :many
SELECT u."id" FROM "Upload" AS u
LEFT JOIN "Material" AS m ON m."uploadId" = u."id"
WHERE u."createdAt" < $1 AND m."id" IS NULL
  AND NOT EXISTS (SELECT 1 FROM "Material" AS mm WHERE mm."url" = '/api/uploads/' || u."id")
  AND NOT EXISTS (SELECT 1 FROM "Card" AS c WHERE c."image" = '/api/uploads/' || u."id")
ORDER BY u."createdAt"
`

// Uploads older than the cutoff that nothing uses: no material row points at them and neither a
// material url nor a card image still names their bytes.
func (q *Queries) ListSweepableUploads(ctx context.Context, createdat time.Time) ([]string, error) {
	rows, err := q.db.Query(ctx, listSweepableUploads, createdat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadIDs = `-- name: ListUploadIDs :many
SELECT "id" FROM "Upload"
`

func (q *Queries) ListUploadIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listUploadIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
