// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package store

import (
	"context"
	"time"
)

const createUpload = `-- name: CreateUpload :exec
INSERT INTO "Upload" ("id", "userId", "mime", "name", "size", "sha256", "pages", "pageBreaks", "extraction", "textHash")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateUploadParams struct {
	ID         string
	UserID     string
	Mime       string
	Name       string
	Size       int32
	Sha256     *string
	Pages      *int32
	PageBreaks []int32
	Extraction *string
	TextHash   *string
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) error {
	_, err := q.db.Exec(ctx, createUpload,
		arg.ID,
		arg.UserID,
		arg.Mime,
		arg.Name,
		arg.Size,
		arg.Sha256,
		arg.Pages,
		arg.PageBreaks,
		arg.Extraction,
		arg.TextHash,
	)
	return err
}

const createUploadImage = `-- name: CreateUploadImage :exec
INSERT INTO "UploadImage" ("id", "uploadId", "page", "order", "paragraph", "anchor", "x", "y", "w", "h", "width", "height", "mime", "context")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateUploadImageParams struct {
	ID        string
	UploadID  string
	Page      int32
	Order     int32
	Paragraph int32
	Anchor    int32
	X         float64
	Y         float64
	W         float64
	H         float64
	Width     int32
	Height    int32
	Mime      string
	Context   string
}

func (q *Queries) CreateUploadImage(ctx context.Context, arg CreateUploadImageParams) error {
	_, err := q.db.Exec(ctx, createUploadImage,
		arg.ID,
		arg.UploadID,
		arg.Page,
		arg.Order,
		arg.Paragraph,
		arg.Anchor,
		arg.X,
		arg.Y,
		arg.W,
		arg.H,
		arg.Width,
		arg.Height,
		arg.Mime,
		arg.Context,
	)
	return err
}

const deleteOwnedUpload = `-- name: DeleteOwnedUpload :execrows
DELETE FROM "Upload" WHERE "id" = $1 AND "userId" = $2
`

type DeleteOwnedUploadParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteOwnedUpload(ctx context.Context, arg DeleteOwnedUploadParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOwnedUpload, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUploads = `-- name: DeleteUploads :exec
DELETE FROM "Upload" WHERE "userId" = $1 AND "id" = ANY($2::text[])
`

type DeleteUploadsParams struct {
	UserID string
	Ids    []string
}

func (q *Queries) DeleteUploads(ctx context.Context, arg DeleteUploadsParams) error {
	_, err := q.db.Exec(ctx, deleteUploads, arg.UserID, arg.Ids)
	return err
}

const getOwnedUpload = `-- name: GetOwnedUpload :one
SELECT "id", "mime", "name", "size", "sha256" FROM "Upload" WHERE "id" = $1 AND "userId" = $2
`

type GetOwnedUploadParams struct {
	ID     string
	UserID string
}

type GetOwnedUploadRow struct {
	ID     string
	Mime   string
	Name   string
	Size   int32
	Sha256 *string
}

func (q *Queries) GetOwnedUpload(ctx context.Context, arg GetOwnedUploadParams) (GetOwnedUploadRow, error) {
	row := q.db.QueryRow(ctx, getOwnedUpload, arg.ID, arg.UserID)
	var i GetOwnedUploadRow
	err := row.Scan(
		&i.ID,
		&i.Mime,
		&i.Name,
		&i.Size,
		&i.Sha256,
	)
	return i, err
}

const getOwnedUploadImage = `-- name: GetOwnedUploadImage :one
SELECT i."id", i."mime" FROM "UploadImage" AS i JOIN "Upload" AS u ON u."id" = i."uploadId"
WHERE i."id" = $1 AND i."uploadId" = $2 AND u."userId" = $3
`

type GetOwnedUploadImageParams struct {
	ID       string
	UploadID string
	UserID   string
}

type GetOwnedUploadImageRow struct {
	ID   string
	Mime string
}

func (q *Queries) GetOwnedUploadImage(ctx context.Context, arg GetOwnedUploadImageParams) (GetOwnedUploadImageRow, error) {
	row := q.db.QueryRow(ctx, getOwnedUploadImage, arg.ID, arg.UploadID, arg.UserID)
	var i GetOwnedUploadImageRow
	err := row.Scan(&i.ID, &i.Mime)
	return i, err
}

const listCardImagesIn = `-- name: ListCardImagesIn :many
SELECT "image" FROM "Card" WHERE "userId" = $1 AND "image" = ANY($2::text[])
`

type ListCardImagesInParams struct {
	UserID string
	Urls   []string
}

func (q *Queries) ListCardImagesIn(ctx context.Context, arg ListCardImagesInParams) ([]*string, error) {
	rows, err := q.db.Query(ctx, listCardImagesIn, arg.UserID, arg.Urls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var image *string
		if err := rows.Scan(&image); err != nil {
			return nil, err
		}
		items = append(items, image)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialUrlsIn = `-- name: ListMaterialUrlsIn :many
SELECT "url" FROM "Material" WHERE "userId" = $1 AND "url" = ANY($2::text[])
`

type ListMaterialUrlsInParams struct {
	UserID string
	Urls   []string
}

func (q *Queries) ListMaterialUrlsIn(ctx context.Context, arg ListMaterialUrlsInParams) ([]*string, error) {
	rows, err := q.db.Query(ctx, listMaterialUrlsIn, arg.UserID, arg.Urls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var url *string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleUnlinkedUploads = `-- name: ListStaleUnlinkedUploads :many
SELECT u."id" FROM "Upload" AS u LEFT JOIN "Material" AS m ON m."uploadId" = u."id"
WHERE u."userId" = $1 AND u."createdAt" < $2 AND m."id" IS NULL
`

type ListStaleUnlinkedUploadsParams struct {
	UserID    string
	CreatedAt time.Time
}

func (q *Queries) ListStaleUnlinkedUploads(ctx context.Context, arg ListStaleUnlinkedUploadsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listStaleUnlinkedUploads, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUploadSha = `-- name: SetUploadSha :exec
UPDATE "Upload" SET "sha256" = $2 WHERE "id" = $1
`

type SetUploadShaParams struct {
	ID     string
	Sha256 *string
}

func (q *Queries) SetUploadSha(ctx context.Context, arg SetUploadShaParams) error {
	_, err := q.db.Exec(ctx, setUploadSha, arg.ID, arg.Sha256)
	return err
}
