// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM "User"
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "User" ("id", "name", "nickname", "role") VALUES ($1, $2, $3, $4) RETURNING id, name, nickname, role, school, grade, streak, points, suspended, "selectedChildId", "srsMode", "desiredRetention", privacy, "completedSubjects", "linkFailures", "linkLockedUntil", "createdAt"
`

type CreateUserParams struct {
	ID       string
	Name     string
	Nickname string
	Role     Role
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Nickname,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Role,
		&i.School,
		&i.Grade,
		&i.Streak,
		&i.Points,
		&i.Suspended,
		&i.SelectedChildID,
		&i.SrsMode,
		&i.DesiredRetention,
		&i.Privacy,
		&i.CompletedSubjects,
		&i.LinkFailures,
		&i.LinkLockedUntil,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, nickname, role, school, grade, streak, points, suspended, "selectedChildId", "srsMode", "desiredRetention", privacy, "completedSubjects", "linkFailures", "linkLockedUntil", "createdAt" FROM "User" WHERE "id" = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Role,
		&i.School,
		&i.Grade,
		&i.Streak,
		&i.Points,
		&i.Suspended,
		&i.SelectedChildID,
		&i.SrsMode,
		&i.DesiredRetention,
		&i.Privacy,
		&i.CompletedSubjects,
		&i.LinkFailures,
		&i.LinkLockedUntil,
		&i.CreatedAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, name, nickname, role, school, grade, streak, points, suspended, "selectedChildId", "srsMode", "desiredRetention", privacy, "completedSubjects", "linkFailures", "linkLockedUntil", "createdAt" FROM "User" WHERE "id" = $1 FOR UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Role,
		&i.School,
		&i.Grade,
		&i.Streak,
		&i.Points,
		&i.Suspended,
		&i.SelectedChildID,
		&i.SrsMode,
		&i.DesiredRetention,
		&i.Privacy,
		&i.CompletedSubjects,
		&i.LinkFailures,
		&i.LinkLockedUntil,
		&i.CreatedAt,
	)
	return i, err
}

const setSelectedChild = `-- name: SetSelectedChild :exec
UPDATE "User" SET "selectedChildId" = $2 WHERE "id" = $1
`

type SetSelectedChildParams struct {
	ID              string
	SelectedChildID *string
}

func (q *Queries) SetSelectedChild(ctx context.Context, arg SetSelectedChildParams) error {
	_, err := q.db.Exec(ctx, setSelectedChild, arg.ID, arg.SelectedChildID)
	return err
}

const updateUserSuspended = `-- name: UpdateUserSuspended :one
UPDATE "User" SET "suspended" = $2 WHERE "id" = $1 RETURNING "id", "suspended"
`

type UpdateUserSuspendedParams struct {
	ID        string
	Suspended bool
}

type UpdateUserSuspendedRow struct {
	ID        string
	Suspended bool
}

func (q *Queries) UpdateUserSuspended(ctx context.Context, arg UpdateUserSuspendedParams) (UpdateUserSuspendedRow, error) {
	row := q.db.QueryRow(ctx, updateUserSuspended, arg.ID, arg.Suspended)
	var i UpdateUserSuspendedRow
	err := row.Scan(&i.ID, &i.Suspended)
	return i, err
}
