// Writes the memoryz-cloud ledger index into GATES.md between the markers below, measured with
// `unlazy-check --status` on every ledger at the moment it runs (never typed by hand). The ledgers
// themselves live under .unlazy/ (ignored); this table is the committed record of their state.
// Usage: node scripts/gates-index.mjs [--check]   (--check fails if GATES.md is out of date)
import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const CHECKER =
  process.env.UNLAZY_CHECK ?? join(homedir(), '.claude/skills/unlazy/bin/unlazy-check');
const DIR = '.unlazy/memoryz-cloud/gates';
const BEGIN = '<!-- memoryz-cloud index: generated by scripts/gates-index.mjs -->';
const END = '<!-- /memoryz-cloud index -->';

if (!existsSync(CHECKER)) throw new Error(`unlazy-check not found at ${CHECKER}`);
const order = (name) =>
  name
    .replace(/\.md$/, '')
    .replace(/^(leaf|node)-/, '')
    .split('.')
    .map(Number);
const files = readdirSync(DIR)
  .filter((f) => f.endsWith('.md'))
  .sort((a, b) => {
    const [x, y] = [order(a), order(b)];
    for (let i = 0; i < Math.max(x.length, y.length); i++)
      if ((x[i] ?? -1) !== (y[i] ?? -1)) return (x[i] ?? -1) - (y[i] ?? -1);
    return a.startsWith('node') ? -1 : 1;
  });

let met = 0;
let unmet = 0;
let abandoned = 0;
const rows = files.map((file) => {
  let out;
  try {
    out = execFileSync(CHECKER, ['--status', join(DIR, file), '--root', process.cwd()], {
      encoding: 'utf8',
    });
  } catch (e) {
    out = `${e.stdout ?? ''}${e.stderr ?? ''}`;
  }
  const title = readFileSync(join(DIR, file), 'utf8')
    .split('\n')[0]
    .replace(/^# Gates:\s*/, '');
  const all = /^ALL MET \((\d+) met\)/m.exec(out);
  const some = /^UNMET: (\d+) \(met: (\d+)/m.exec(out);
  const open = [...out.matchAll(/^\s+UNMET (\S+?)(?: \(|: )/gm)].map((m) => m[1].split(':').pop());
  const gone = (readFileSync(join(DIR, file), 'utf8').match(/^ABANDON: \S+/gm) ?? []).map(
    (l) => l.split(' ')[1],
  );
  if (!all && !some) throw new Error(`cannot read the status of ${file}:\n${out}`);
  const m = all ? Number(all[1]) : Number(some[2]);
  const u = all ? 0 : Number(some[1]);
  met += m;
  unmet += u;
  abandoned += gone.length;
  const state = u === 0 ? 'ALL MET' : `open: ${open.join(', ')}`;
  return `| ${file.replace(/\.md$/, '')} | ${title.replace(/\|/g, '/')} | ${m} | ${u} | ${state}${gone.length ? `; abandoned: ${gone.join(', ')}` : ''} |`;
});

const measured = new Date().toISOString().slice(0, 16).replace('T', ' ') + ' UTC';
const block = `${BEGIN}
## memoryz-cloud — Go 서버 · GCP · 도메인 (원장 색인)

원장 본문은 \`.unlazy/memoryz-cloud/gates/\`(무시됨), 계획은 \`.unlazy/memoryz-cloud/PLAN.md\`. 아래 표는 ${measured} 에 \`unlazy-check --status\` 로 잰 값이다.

| 원장 | 범위 | 충족 | 미충족 | 상태 |
| --- | --- | --- | --- | --- |
${rows.join('\n')}

합계: 충족 ${met} · 미충족 ${unmet} · 포기 ${abandoned}.
${END}`;

const current = readFileSync('GATES.md', 'utf8');
const next = current.includes(BEGIN)
  ? current.slice(0, current.indexOf(BEGIN)) +
    block +
    current.slice(current.indexOf(END) + END.length)
  : `${current.trimEnd()}\n\n${block}\n`;
const strip = (text) => text.replace(/표는 .* UTC 에/, '표는 <time> 에');
if (process.argv.includes('--check')) {
  if (strip(next) !== strip(current)) {
    console.error('GATES.md index is out of date: run node scripts/gates-index.mjs');
    process.exit(1);
  }
  console.log(
    `GATES_INDEX_CURRENT ledgers=${files.length} met=${met} unmet=${unmet} abandoned=${abandoned}`,
  );
} else {
  writeFileSync('GATES.md', next);
  console.log(
    `GATES_INDEX_WRITTEN ledgers=${files.length} met=${met} unmet=${unmet} abandoned=${abandoned}`,
  );
}
