#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Google sign-in for memoryz (leaf-3.3). Run from the repository root:
#   bash scripts/oauth-wizard.sh
# The Console steps need a human signed in as innovoedutech@gmail.com and the
# human's own acceptance of Google's user data policy; the client secret goes
# from a hidden prompt straight into Secret Manager and is never printed.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

PROJECT=memoryz-prod
REGION=asia-northeast3
ORIGIN=https://memoryz.kr
CALLBACK="$ORIGIN/api/auth/google/callback"
SA=memoryz-run@memoryz-prod.iam.gserviceaccount.com
OWNER=innovoedutech@gmail.com
export CLOUDSDK_ACTIVE_CONFIG_NAME=memoryz
# Nothing here is written to .env: the values live in Secret Manager only.
ENV_FILE="$(mktemp)"
trap 'rm -f "$ENV_FILE"; unset GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET' EXIT

cd "$(dirname "$0")/.."

# put_gcp_secret NAME VALUE creates the secret on first use (Seoul replica, like the others),
# adds VALUE as a new version from stdin, and lets the service account read it.
put_gcp_secret() {
  local name="$1" value="$2"
  if ! gcloud secrets describe "$name" --project="$PROJECT" >/dev/null 2>&1; then
    gcloud secrets create "$name" --project="$PROJECT" --replication-policy=user-managed --locations="$REGION" --labels=app=memoryz >/dev/null
  fi
  printf '%s' "$value" | gcloud secrets versions add "$name" --project="$PROJECT" --data-file=- >/dev/null
  gcloud secrets add-iam-policy-binding "$name" --project="$PROJECT" \
    --member="serviceAccount:$SA" --role=roles/secretmanager.secretAccessor >/dev/null
  printf '  %s✓ stored%s %s in Secret Manager (value not shown)\n' "$GREEN" "$RESET" "$name"
}

# Preflight: the right gcloud account, and the domain cutover already done.
account="$(gcloud config get-value account 2>/dev/null || true)"
if [[ "$account" != "$OWNER" ]]; then
  printf '%sgcloud config "memoryz" is signed in as "%s", not %s.%s\n' "$RED" "$account" "$OWNER" "$RESET"
  printf 'Run: CLOUDSDK_ACTIVE_CONFIG_NAME=memoryz gcloud auth login %s\n' "$OWNER"
  exit 1
fi
app_url="$(gcloud run services describe memoryz --region="$REGION" --project="$PROJECT" --format=json \
  | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{const e=JSON.parse(s).spec.template.spec.containers[0].env||[];process.stdout.write((e.find(x=>x.name==='APP_URL')||{}).value||'')})")"
if [[ "$app_url" != "$ORIGIN" ]]; then
  printf '%sThe service still answers at %s, not %s.%s\n' "$RED" "${app_url:-?}" "$ORIGIN" "$RESET"
  printf 'Finish the domain cutover first (docs/CLOUD.md, 도메인), then run this again.\n'
  exit 1
fi

banner "memoryz · Google 로그인 설정"

stage "Console 에 innovoedutech 로 들어가기"
say "Google 인증 플랫폼을 memoryz-prod 프로젝트로 엽니다."
open_url "https://console.cloud.google.com/auth/overview?project=$PROJECT"
step "오른쪽 위 계정 사진을 눌러 $OWNER 로 전환하세요 (없으면 '다른 계정 추가')."
step "'추가 액세스 권한 필요' 대신 Google 인증 플랫폼 개요가 보이면 됩니다."
pause "개요 화면이 보이면 Enter"

stage "브랜딩 (앱 정보 · 약관 동의)"
open_url "https://console.cloud.google.com/auth/branding?project=$PROJECT"
say "처음이면 '시작하기' 마법사가 뜹니다. 순서대로 입력하세요:"
step "앱 정보 → 앱 이름: Memoryz · 사용자 지원 이메일: $OWNER"
step "대상 → 외부"
step "연락처 정보 → $OWNER"
step "완료 → 'Google API 서비스: 사용자 데이터 정책'을 직접 읽고 동의한 뒤 '만들기'"
say "그다음 브랜딩 화면에서:"
step "승인된 도메인 → '도메인 추가' → memoryz.kr → 저장"
step "애플리케이션 홈페이지 → $ORIGIN (선택)"
warn "앱 로고는 올리지 마세요. 로고가 있으면 Google 의 브랜드 검증을 거쳐야 게시됩니다."
pause "브랜딩을 저장했으면 Enter"

stage "대상 → 프로덕션으로 게시"
open_url "https://console.cloud.google.com/auth/audience?project=$PROJECT"
step "사용자 유형이 '외부'인지 확인"
step "게시 상태 '테스트 중' 옆 '앱 게시' → 확인 대화상자에서 '확인'"
note "기본 범위(openid·profile)만 쓰므로 검증 없이 바로 '프로덕션 단계'가 됩니다."
note "테스트 모드로 두면 테스트 사용자 100명까지만 로그인할 수 있어 학생·학부모가 막힙니다."
pause "게시 상태가 '프로덕션 단계'이면 Enter"

stage "데이터 액세스 (범위)"
open_url "https://console.cloud.google.com/auth/scopes?project=$PROJECT"
step "'범위 추가 또는 삭제' → 'openid' 와 '.../auth/userinfo.profile' 두 개만 체크 → 업데이트"
step "userinfo.email 은 넣지 마세요 (학생 이메일을 받지 않습니다)."
step "'저장'"
pause "두 범위가 저장됐으면 Enter"

stage "웹 클라이언트 만들기"
open_url "https://console.cloud.google.com/auth/clients/create?project=$PROJECT"
step "애플리케이션 유형: 웹 애플리케이션 · 이름: memoryz-web"
step "승인된 자바스크립트 원본 → URI 추가 → $ORIGIN"
step "승인된 리디렉션 URI → URI 추가 → $CALLBACK"
step "'만들기' → 뜨는 창에 클라이언트 ID 와 클라이언트 보안 비밀번호가 보입니다."
warn "보안 비밀번호는 이 창에서만 복사할 수 있습니다. 창을 닫기 전에 아래에 붙여 넣으세요."
GOOGLE_CLIENT_ID=""
until [[ "$GOOGLE_CLIENT_ID" =~ ^[0-9]+-[a-z0-9]+\.apps\.googleusercontent\.com$ ]]; do
  ask GOOGLE_CLIENT_ID "클라이언트 ID 붙여 넣기 (…apps.googleusercontent.com):"
  GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID//[[:space:]]/}"
done
GOOGLE_CLIENT_SECRET=""
until [[ "$GOOGLE_CLIENT_SECRET" =~ ^GOCSPX-[A-Za-z0-9_-]{20,}$ ]]; do
  ask_secret GOOGLE_CLIENT_SECRET "클라이언트 보안 비밀번호 붙여 넣기 (입력은 보이지 않습니다, GOCSPX-…):"
  GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET//[[:space:]]/}"
done
printf '  %s✓ captured%s client ID and secret (secret kept in memory only)\n' "$GREEN" "$RESET"

stage "Secret Manager 에 저장"
say "두 값을 memoryz-prod 의 Secret Manager 에 새 버전으로 넣고, 서비스 계정만 읽게 합니다."
if ! confirm "GOOGLE_CLIENT_ID · GOOGLE_CLIENT_SECRET 을 저장할까요?"; then
  warn "저장하지 않고 멈춥니다. 다시 실행하면 이 단계부터 이어서 할 수 있습니다."
  exit 1
fi
put_gcp_secret GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
put_gcp_secret GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
unset GOOGLE_CLIENT_SECRET
node scripts/deploy.mjs verify-oauth

stage "서비스에 반영하고 확인"
current_tag="$(gcloud run services describe memoryz --region="$REGION" --project="$PROJECT" --format='value(spec.template.spec.containers[0].image)')"
current_tag="${current_tag##*:}"
say "지금 실행 중인 이미지($current_tag)를 그대로 다시 배포해 두 시크릿을 환경 변수로 붙입니다."
if ! confirm "Cloud Run 서비스 memoryz 를 다시 배포할까요? (1~2분, 무중단)"; then
  warn "배포하지 않았습니다: node scripts/deploy.mjs service --tag $current_tag"
  SKIPPED+=("redeploy: node scripts/deploy.mjs service --tag $current_tag")
else
  node scripts/deploy.mjs service --tag "$current_tag"
  node scripts/deploy.mjs verify-service
  node scripts/cloud-smoke.mjs --oauth
fi
pause "결과에 CLOUD_OAUTH_OK 가 보이면 Enter"

stage "직접 한 번 로그인"
open_url "$ORIGIN"
step "로그아웃 상태에서 'Google 로 시작하기' → 본인 Google 계정 선택 → 동의"
step "학생 역할로 홈 화면이 그려지는지 봅니다 (처음이면 온보딩 화면이 먼저 나옵니다)."
if confirm "Google 로그인으로 홈(또는 온보딩)까지 들어갔나요?"; then
  printf '%s leaf-3.3 O3 user confirmed a real Google sign-in at %s (oauth-wizard)\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$ORIGIN" >> .unlazy/memoryz-cloud/status.log
  printf '  %s✓ recorded%s in .unlazy/memoryz-cloud/status.log\n' "$GREEN" "$RESET"
else
  SKIPPED+=("real Google sign-in at $ORIGIN (tell Claude what the screen showed)")
fi

finish
